### ISSUE TITLE
can't add members to the channel, please help

### ISSUE THREAD

**Issue by ravichoudhary33** [twilio/twilio-chat-demo-android#10]

**Comment by berkus** [comment]
Any details? Logs? Source code snippets?

**Comment by ravichoudhary33** [comment]
Error adding member. Error 0:50107

**Comment by berkus** [comment]
Error - 50107
User not authorized for command

you should check your service permissions and if this user is allowed to add members

https://www.twilio.com/docs/api/chat/guides/permissions

**Comment by ravichoudhary33** [comment]
thanks @berkus

**Comment by berkus** [comment]
What do you mean by "register user on twilio"?

User identities are ephemeral and Twilio does not care how you call and authenticate them. You can just login as that user and it will be created in the server instance.

**Comment by ravichoudhary33** [comment]
Actually I am getting some fake user name that is generated by java sdk server code. I want to register the user with some specific name instead of  some random name.

**Comment by berkus** [comment]
I don't know what you mean.

You as developer control how names are created when you issue the tokens. Use your own token generator.

**Comment by ravichoudhary33** [comment]
@berkus i am able to create accesstoken by using twilio java sdk in eclipse but when i include the same library in android studio project i am getting lot's of error.

**Comment by berkus** [comment]
If you still have token generator questions, please open a new ticket. Closing this one.
