### ISSUE TITLE
IONIC 3 Twlio error : Cannot find name 'unknown'

### ISSUE THREAD

**Issue by tarunmishra592** [twilio/twilio-chat-demo-android#103]
Hey @twlio Can you please help with this error.
I am using twlio-chat in ionic 3.

[app-scripts] [13:13:00]  typescript: node_modules/twilio-chat/lib/session.d.ts, line: 38 
[app-scripts]             Cannot find name 'unknown'. 
[app-scripts]       L38:  addCommand(action: string, params: Object): Promise<unknown>;
[app-scripts]             Cannot find name 'unknown'. 
[app-scripts] [13:13:00]  typescript: node_modules/twilio-sync/lib/syncmap.d.ts, line: 63 
[app-scripts]       L63:  forEach(handler: any): Promise<unknown>;
[app-scripts]       L64:  private shouldIgnoreEvent;
[app-scripts]             Initializers are not allowed in ambient contexts. 
[app-scripts] [13:13:00]  typescript: node_modules/twilsock/lib/protocol/messages/reply.d.ts, line: 5 
[app-scripts]        L4:  readonly method: Protocol.MessageType;
[app-scripts]        L5:  readonly payload_type = "application/json";
[app-scripts]        L6:  readonly status: {

**Comment by aleksandrsivanovs** [comment]
H!

it seems like old typescript definition (judging by https://github.com/angular/angular-cli/issues/5693)

can you update to latest twilio-chat and latest typescript definitions?
(also, it's better to ask JS/TS questions in https://github.com/twilio/twilio-chat-console-webapp.js)

Aleksandrs

**Comment by pretzelpanda** [comment]
service-worker/service-worker.d.ts(204,55): error TS2304: Cannot find name 'unknown'.
----


same issue?

**Comment by berkus** [comment]
Could be, but it's not related to android client. It's better to ask JS/TS questions in https://github.com/twilio/twilio-chat-console-webapp.js

**Comment by berkus** [comment]
Closing as not relevant to android SDK.
