### ISSUE TITLE
User unsubscribe() method not working as expected

### ISSUE THREAD

**Issue by fede87** [twilio/twilio-chat-demo-android#106]
### Description

Calling unsubscribe method on a subscribed user prevents that the same user can be subscribed again.
The next time the member.getAndSubscribeUser(callback) method is called the CallbackListener<User> callback is never going to be triggered neither with the onError(erroInfo).
The same flow was working instead on v3.1.1 version.
The same [issue](https://github.com/twilio/twilio-chat-demo-ios/issues/51) is present also on iOS Chat SDK.

### Steps to Reproduce

1. call member.getAndSubscribeUser(callback) or client.users.getAndSubscribeUser(identity, callback) and wait for the onSuccess(user) callback has been called.
2. call user.unsubscribe() when the user's updates are no longer needed.
3. go thru step 1 again but callback will no longer be triggered

#### Code

This use case has been tested on the demo app and can be easily reproduced adding the following code to MessageActivity.kt:

```kotlin
    override fun onDestroy() {
        channel?.removeListener(this@MessageActivity)
        TwilioApplication.instance.basicClient.chatClient?.users?.subscribedUsers?.forEach {
            it.unsubscribe()
        }
        super.onDestroy()
    }
```

#### Expected Behavior

We expect to be able to subscribe to the same user again after some time.

#### Chat Android SDK

v4.2.3

#### Android API

Tested on api 26, 28 and 29

**Comment by rusmonster** [comment]
fixed in v4.2.5
