### ISSUE TITLE
Support for older devices

### ISSUE THREAD

**Issue by berkus** [twilio/twilio-chat-demo-android#108]
We are planning to lower required API level on Android devices to hopefully API 19.

Forked from discussion in #56

**Comment by sfseyhan** [comment]
To answer the question about our minSdk in linked thread #56 , we are supporting api 19 and need to keep supporting it.

Our most frequent crashes are from twilio at the moment and it seems like it will worsen if 3.1.1 version causes crashes with android 10 as it was mentioned in #56 

We really look forward for 4.x.x versions to support api 19 so we can update asap.

**Comment by berkus** [comment]
We're working on it!

**Comment by rusmonster** [comment]
SDK v4.2.5 has minimum API level 19

**Comment by fede87** [comment]
We have tested v.4.2.5 on various emulators and devices with api level between 16 and 19.

Tested devices:

- Samsung S1 (api 16, armv7a)
- Samsung S3 (api 18, armv7a)
- Emulator (api 16, x86)
- Emulator (api 17, x86)
- Emulator (api 18, x86)

All the tests passed and the SDK seems to be working.

Are there any reasons not to use the SDK with those api levels?
Thanks.

**Comment by rusmonster** [comment]
@fede87 The main reason is we are unable to test it on devices with API below 19 as they are not present in the Firebase Test Lab which we use for running our tests.

BTW there are no any reasons why it shouldn't work on API 16

So If you tested it for your use cases and you are sure it works - you can use
```
<uses-sdk
     android:minSdkVersion="16"
     android:targetSdkVersion="28"
     tools:overrideLibrary="com.twilio.chat" />
```
In your `AndroidManifest` In order to override the `minSdkVersion`

**Comment by InI4** [comment]
I know, this is closed, but in a short test I can confirm running on the following device:

- Samsung Galaxy S4 Active, Android 4.2.2 (SDK 17)

Cool!
