### ISSUE TITLE
onNewMessageNotification

### ISSUE THREAD

**Issue by InI4** [twilio/twilio-chat-demo-android#109]
### Description

#89 is still open #108 is closed now. I wanted to state, that there are issues on Android 17 which might also be fixable, though out of your claims: I can obtain the following exception from Twilio:

`10-24 07:39:11.099 de.spieleck.app.badgers.debug I/dalvikvm: Could not find method org.json.JSONObject.wrap, referenced from method com.twilio.chat.ChatClient.handleNotification
`

I think `JSONObject.wrap()` is a static convenience method and things can be done without, especially when you know the objects you treat.

### Steps to Reproduce

1. Construct a Twilio Chat client and get FCM notifications
2. Call `client.handleNotification(payload);`
3. receive above `Exception`.

#### Expected Behavior

No Exception. 

I was actually researching why 

`ChatClientListener.onNewMessageNotification(...)`

does not get called on a device. But this is probably a consequence of the problem above.

#### Actual Behavior

Fails to handle Notification.

#### Reproduces how Often

Completely deterministic given the appropriate device.

#### Logs

I think I have stated the problem clearly, but here is a line of logs: 

`10-24 07:39:11.099 de.spieleck.app.badgers.debug I/dalvikvm: Could not find method org.json.JSONObject.wrap, referenced from method com.twilio.chat.ChatClient.handleNotification
    java.lang.NoSuchMethodError: org.json.JSONObject.wrap
        at com.twilio.chat.ChatClient.handleNotification(sf:624)
`

#### Chat Android SDK

`com.twilio:chat-android:4.2.5`

#### Android API

4.2.2 or SDK 17 reproduces this

#### Android Device

Samsung S4 Active

**Comment by berkus** [comment]
Hi, we've implemented a workaround for this, will be released soon!

**Comment by InI4** [comment]
@berkus looking forward to this, any prognosis, when it could be?

**Comment by berkus** [comment]
We plan to release next week, maybe sooner if all testing goes smooth.

**Comment by InI4** [comment]
Na, this took a bit longer. Anyway, first tests here look good, the notifications go through live even on an ancient Android 4.2.2 test device! Will do some more QA though.

**Comment by berkus** [comment]
👍

**Comment by InI4** [comment]
Works for me and my tests. Cannot generalize to all Android 4.2.2 devices though.
