### ISSUE TITLE
not getting any notification about message, please help

### ISSUE THREAD

**Issue by ravichoudhary33** [twilio/twilio-chat-demo-android#11]

**Comment by berkus** [comment]
A description of the problem would be nice, for a start.

**Comment by ravichoudhary33** [comment]
hi @berkus actually i want to notify the user when a new message comes, for that i have configured the push notification properly and i am able to receive notification when i send some message from firebase console but i am not getting any notification when channel user send message to the channel, please let me know what should i do in order to achieve that

**Comment by ravichoudhary33** [comment]
resolved the issue...

**Comment by supragyanmandal** [comment]
I am having the same issue can you please help what is the solution

**Comment by supragyanmandal** [comment]
> resolved the issue...

how you solved this issue?
