### ISSUE TITLE
Reply to message feature

### ISSUE THREAD

**Issue by niliyam** [twilio/twilio-chat-demo-android#115]
Is there a way to configure reply to an individual message in a chat, like in whatsapp? 

I could not find such thing in the Twilio Chat SDK or by searching.

#### Chat Android SDK

4.2.6

#### Android API

28

#### Android Device

LG G7 Thinq+

**Comment by berkus** [comment]
Hi!

Sure, you can do it.

You'd use Message attributes to record its parent message ID, for example:

`channel.messages.sendMessage(Message.options().withBody(text).withAttributes(`{parent_message_sid: "MSxxxx<message ID you're replying to>xxxx"}`)`

You could also improve this and maintain a thread_id that would let you group all messages related to a single thread similar to Slack threads.

`channel.messages.sendMessage(Message.options().withBody(text).withAttributes("{parent_message_sid: "MSxxxx<message ID you're replying to>xxxx", thread_id: 5}")`

Or you could use some topic_id and do grouping similar to Zulip streams:

`channel.messages.sendMessage(Message.options().withBody(text).withAttributes("{parent_message_sid: "MSxxxx<message ID you're replying to>xxxx", topic_id: "my stream"}")`

Attributes are JSON so you can do even all three options at the same time, or let users choose.
