### ISSUE TITLE
Unable to fetch Channel data 

### ISSUE THREAD

**Issue by niliyam** [twilio/twilio-chat-demo-android#116]
### Description

I am able to create the Chat Client successfully. After doing this, i am trying to get the channels. 
But i am not getting the channels instantly.
Also if i do get the channels, i am not getting the channel attributes.

If i wait for 5-10 seconds, then this data comes successfully.

I have tried to implement a ProgressDialog, but am not able to because the ChatClientListener methods do not get called.
**onClientSynchronization()** method never gets called.

How do i handle this?

#### Reproduces how Often

95%

#### Chat Android SDK

4.2.6

#### Android API

28

#### Android Device

LG G7 ThinQ+

**Comment by niliyam** [comment]
Hi Any update on this ??

**Comment by rusmonster** [comment]
Hi!
1. Please clarify what do you mean `not getting the channels instantly`? Getting channels first time after creating a client required network request which takes some reasonable time.
2. `not getting the channel attributes` on time is known issue. Current ETA to deliver a fix is one month.
3. Please provide debug log with your case when `onClientSynchronization() method never gets called.` (Call `ChatClient.setLogLevel(LogLevel.VERBOSE)` before creating a client to enable logging)

**Comment by berkus** [comment]
2. Channel attributes are fixed in release [4.2.9](https://www.twilio.com/docs/chat/android/changelog#programmable-chat-android-429-jan-21-2020).
