### ISSUE TITLE
OnError is called only after 3 minutes when send message is called on no Internet connection

### ISSUE THREAD

**Issue by lectricas** [twilio/twilio-chat-demo-android#119]
Hi. This is not a bug I guess(as you have resend on available feature) but rather a question.
Is there any way to reduce this giant timeout?

**Comment by rusmonster** [comment]
@lectricas no way a the moment. We are going to make this timeout configurable in coming releases, but no ETA yet.

**Comment by berkus** [comment]
Configurable command timeout is implemented in SDK now, you could specify a preferred time out value.
