### ISSUE TITLE
What is the use of RegistrationIntentService?

### ISSUE THREAD

**Issue by ajitdubey-mob-ibtech** [twilio/twilio-chat-demo-android#12]
In programmable android chat sdk we are using RegistrationIntentService even we are not using in Programmable voice android sdk.
I think without RegistrationIntentService we can get FCM access token. 
Kindly confirm we should use or not?

**Comment by berkus** [comment]
In the demo app we're following Google-recommended way of getting and FCM token. But it's just a demo application; if you use some other way of obtaining that token - feel free to code however you want.

**Comment by ajitdubey-mob-ibtech** [comment]
Yeah!
Thanks for your response.

**Comment by berkus** [comment]
Cool, I'll close it - open a new one if you have any other questions.
