### ISSUE TITLE
Media Notification is not working in twilio sdk...

### ISSUE THREAD

**Issue by pintuag** [twilio/twilio-chat-demo-android#123]
Before filing an issue please check that the issue is not already addressed by the following:
* [Github Issues](https://github.com/twilio/twilio-chat-demo-android/issues)
* [Changelog](https://www.twilio.com/docs/api/chat/changelogs/android)

Remove the above lines from the template! Fill in ALL fields in the following:

### Description

[Description of the issue]

### Steps to Reproduce

1. [Step one]
2. [Step two]
3. [Insert as many steps as needed]

#### Code (optional)

```java
// Code that help reproduce the issue
```

#### Expected Behavior

[What you expect to happen]

#### Actual Behavior

[What actually happens]

#### Reproduces how Often

[What percentage of the time does it reproduce?]

#### Logs

Please collect logs as described [here](https://github.com/twilio/twilio-chat-demo-android/blob/master/REPORT_BUGS.md). Full unedited logs help reproduce and fix issues faster.

```
// Log output when issue occurs
```

Or attach it as a file.

#### Logs

Yes, if you didn't collect the logs as described above, please collect the logs. Do not file the issue if you don't have enough information, this means having some logs, too.

#### Logs

Yes, seriously. Please send logs!

### Versions

All relevant version information for issue, fill in below:

#### Chat Android SDK

Which SDK version did you use? [eg. 2.0.8]

#### Android API

On which Android API version or versions does it happen? [eg. 18]

#### Android Device

Device or devices on which the problem happens [eg. Nexus 5]

**Comment by berkus** [comment]
Nothing is filed in the bug, closing.
