### ISSUE TITLE
Application taking too much time to login

### ISSUE THREAD

**Issue by k9428** [twilio/twilio-chat-demo-android#13]
Application taking too much time to login.
I have attached my full error log
[my_error_log.txt](https://github.com/twilio/twilio-chat-demo-android/files/1186614/my_error_log.txt)

**Comment by berkus** [comment]
The log covers 7 seconds of real time.

Can you please be more specific:
0) which SDK version are you using?
1) how much time does login take?
2) what network are you on?
3) what is your expectation of login time?

**Comment by berkus** [comment]
Closing this as there was no response.

**Comment by madhurtewani-wow** [comment]
Hello @berkus,

I'm facing the same issue.

Please find below answers to your questions:
0. SDK version 2.0.0
1. Infinite time, not login in at all
2. 125 Mbps WiFi network
3. Within 30 seconds

I'm using demo app with base URL to my own server to generate token.

**Comment by berkus** [comment]
@madhurtewani-wow can you please open a support ticket on http://support.twilio.com/ and provide your generated token and logs (logs can be extracted as described [here](https://github.com/twilio/twilio-chat-demo-android/blob/master/REPORT_BUGS.md))
