### ISSUE TITLE
Unable to compile code.

### ISSUE THREAD

**Issue by mayank2212** [twilio/twilio-chat-demo-android#131]
ERROR: Unable to resolve dependency for ':chat-demo-android@debug/compileClasspath': Failed to transform artifact 'chat-android-with-symbols.aar (com.twilio:chat-android-with-symbols:5.0.1)' to match attributes {artifactType=jar}.
Show Details
Affected Modules: chat-demo-android

Getting this message in logcat

**Comment by rusmonster** [comment]
@mayank2212 Thanks for reporting this. 
Fixed by #132
