### ISSUE TITLE
NullPointerException when calling channel.getMessages()

### ISSUE THREAD

**Issue by Gerlac** [twilio/twilio-chat-demo-android#138]
### Description

Getting `NullPointerException` when calling `channel.getMessages()` so we can call `sendMessage()`. We are waiting to receive `Channel.SynchronizationStatus.ALL`  in `onSynchronizationChanged()` before calling `channel.getMessages()`. This bug started to show when we updated from version`4.2.4` to `4.2.9`.  Also happening on `5.0.1`

We are not actively listening to `onSynchronizationChanged()`, so when we receive `Channel.SynchronizationStatus.ALL` once, we assume we can call `channel.getMessages()`. It is not clear from the documentation if it is needed to actively listen to more changes after receiving `Channel.SynchronizationStatus.ALL`. If that is the case some code sample would be appreciated. As stated before, this issue did not show up when using version `4.2.4` of the SDK

### Steps to Reproduce

Not sure how to reproduce this. Seen crash in our crash reporting tool

#### Expected Behavior

Not to crash

#### Actual Behavior

Crashes

#### Logs
```
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'void com.twilio.chat.Messages.sendMessage(com.twilio.chat.Message$Options, com.twilio.chat.CallbackListener)' on a null object reference
```

### Versions

All relevant version information for issue, fill in below:

#### Chat Android SDK

Happening in `4.2.9` and `5.0.1`

#### Android API

Multiple android versions

#### Android Device

Multiple android devices

**Comment by berkus** [comment]
Please attach the log (entire log, not two irrelevant lines).

**Comment by Gerlac** [comment]
The rest of the crash log are just the lines of our app calling the method:
`channel.messages.sendMessage(Message.options().withAttributes(Attributes(attributes)).withBody(text), null)`. I don't think those lines should be relevant to understand the issue. 
Just updated the description to add that this is also happening in `5.0.1`

**Comment by berkus** [comment]
You should collect the logs [correctly, as described](https://github.com/twilio/twilio-chat-demo-android/blob/master/REPORT_BUGS.md).

**Comment by Gerlac** [comment]
Unfortunately, we did not manage to reproduce the bug yet, so we cannot provide debug logs. The only thing we have so far are the crashes from the production app happening consistently since we updated to `4.2.9`.

**Comment by berkus** [comment]
Please upgrade to Conversations 1.1.0, there is no getMessage() function at all and so it should have better API.

**Comment by berkus** [comment]
@Gerlac you're most probably not waiting for [full synchronization](https://www.twilio.com/docs/chat/best-practices-sdk-clients#mobile-sdks-specifics) as described, btw. That must be the reason for the error you're getting.

**Comment by julianfalcionelli** [comment]
@berkus I am facing this issue also when adding members to a just created channel. This is probably because the "synchronization status" that you mentioned, but I am not seeing that the `onClientSynchronization(p0: ChatClient.SynchronizationStatus?)` is called, do I need to trigger something to get that method called or it should be automatically called once we instantiate the chat Client?

**Comment by julianfalcionelli** [comment]
I found a workaround for this, before I was adding the current user and the destiny by calling the members.addByIdentity and now I first call the channel.join and just call the members.addByIdentity for the destiny...
