### ISSUE TITLE
Upload listener not working

### ISSUE THREAD

**Issue by polivmi1** [twilio/twilio-chat-demo-android#139]
@berkus I have reported this https://github.com/twilio/twilio-chat-demo-android/issues/111 

and since few weeks ago the ProgressListener during upload isn't calling onProgress and onCompleted. Upload completes successfully, but these aren't called. Same thing happens on iOS. This seems like a twilio server bug.

Thank you for looking.

**Comment by polivmi1** [comment]
Any updates here?

**Comment by berkus** [comment]
Hi,

highly unlikely it's a server bug, the progress reporting is local to SDK.

Currently media is low priority, as we're preparing other new releases. We will take a close look at it end of September.

**Comment by polivmi1** [comment]
Hi @berkus, do you have timeline on this? We can't properly update attachment upload indicators due to this. We are on the latest 6.1.

**Comment by berkus** [comment]
@rusmonster pls can you take a look?

**Comment by polivmi1** [comment]
@berkus @rusmonster any updates on this one?

**Comment by berkus** [comment]
@polivmi1 Media updates are expected this  year, but only in Twilio Conversations SDK.
