### ISSUE TITLE
how to implement typing indicator in android chat app using twillo?

### ISSUE THREAD

**Issue by ritubansal1** [twilio/twilio-chat-demo-android#140]
> Before filing an issue please check that the issue is not already addressed by the following:
>  * [Github Issues](https://github.com/twilio/twilio-chat-demo-android/issues)
>  * [Changelog](https://www.twilio.com/docs/api/chat/changelogs/android)

### Description

[Description of the issue]

### Steps to Reproduce

1. [Step one]
2. [Step two]
3. [Insert as many steps as needed]

#### Code (optional)

```java
// Code that help reproduce the issue
```

#### Expected Behavior

[What you expect to happen]

#### Actual Behavior

[What actually happens]

#### Reproduces how Often

[What percentage of the time does it reproduce?]

#### Logs

Please collect logs as described [here](https://github.com/twilio/twilio-chat-demo-android/blob/master/REPORT_BUGS.md). Full unedited logs help reproduce and fix issues faster.

```
// Log output when issue occurs
```

Or attach it as a file.

### Versions

All relevant version information for issue.

#### Chat Android SDK

[eg. 2.0.8]

#### Android API

[eg. 18]

#### Android Device

[eg. Nexus 5]

**Comment by berkus** [comment]
Sorry, can you formulate your question? I see only default issue template pasted here.

**Comment by berkus** [comment]
No response, closing.
