### ISSUE TITLE
Socket Time Exception on Samsung devices when using 4G mobile data. 

### ISSUE THREAD

**Issue by srb9181** [twilio/twilio-chat-demo-android#144]
@berkus I am creating client by passing twilio token in Samsung Devices as follows -
```
if (chatClient == null) {
            Logger.log("locsend -> chatClient null")
            assert(chatClient == null)
            val props = ChatClient.Properties.Builder()
                .createProperties()
            ChatClient.create(context, token!!, props, this)

        }
        else chatClient!!.updateToken(token, object : StatusListener() {
            override fun onSuccess() {
                Logger.log("locsend -> onSuccess")

                (context as HospitalApplication).mutableTokenCreated.postValue(true)
                isTokenExpired.postValue(false)
                chatClientStatus!!.tokenCreated(true)
                Logger.log("chatClient status", " " + chatClient!!.connectionState)
            }

            override fun onError(errorInfo: ErrorInfo?) {
                super.onError(errorInfo)
                Logger.log("locsend -> onError")
                if (chatClientStatus != null && chatClient!!.connectionState == ChatClient.ConnectionState.CONNECTED) chatClientStatus!!.tokenCreated(false)
                isTokenExpired.postValue(true)
            }
        })
```
I am using Twilio android chat sdk version `'com.twilio:chat-android:5.1.1'`

### Description
When I am trying to create Client on **Galaxy Note8** and **Samsung M30** using above method on **4G mobile data**.  
Chat client not getting created. I am getting I am getting SocketTimeoutException on **onError** after long time wait.

#### Expected Behavior
Chat Client created and initialised 

#### Actual Behavior
I am getting SocketTimeoutException on **onError** 
```
override fun onError(errorInfo: ErrorInfo) {
        super.onError(errorInfo)
        if (chatClientStatus != null) chatClientStatus!!.tokenCreated(false)
        Logger.log("locsend -> onError2 ${errorInfo.message}}")
       //here I am getting socket timeout exception 
    }
```

### Versions
I am facing this issues in Android Orio and Pai Samsung devices.

#### Chat Android SDK

Which SDK version did you use? 
'com.twilio:chat-android:5.1.1'

**Comment by rusmonster** [comment]
@srb9181 Please try `v.6.1.0` there was a lot of socket related changes since `v.5.1.1`
If you still have issues please post full log here (see [how to collect logs](https://github.com/twilio/twilio-chat-demo-android/blob/master/REPORT_BUGS.md))

**Comment by srb9181** [comment]
Thank You @rusmonster. Issue I was facing resolved now. I have more query Is twilio still using backoff time to connect in case of internet connection lost. If yes then why do not we use workmanager to establish connection whenever internet connection available and establish client synchronisation. It will work in background as well .

**Comment by berkus** [comment]
@srb9181 i think with the changes we deployed in 6.1.0 we are in position to improve the network detection mechanisms now, so we will look into it.
