### ISSUE TITLE
member.getAttributes() => attributes are always empty

### ISSUE THREAD

**Issue by kostik15** [twilio/twilio-chat-demo-android#146]
Firstly I set some attributes for current user. 

```
JSONObject jsonObject = new JSONObject();
try {
                            jsonObject.put("sex", setupModel.getSex());
                            jsonObject.put("age",setupModel.getAge());
                            jsonObject.put("imageVersion", 0 );
                            jsonObject.put("nickname", setupModel.getNickname());
                        } catch (JSONException e) {
                            e.printStackTrace();
                        }
                        Attributes attributes = new Attributes(jsonObject);
                        user.setAttributes(attributes, new StatusListener() {
```

These properties have been succesfully set and are also visible in console. 
![image](https://user-images.githubusercontent.com/14541273/90984996-1dae7f00-e579-11ea-9983-7bc13fdc721d.png)

I joined random public channel. 
I sent some messages. 

Member and current user on picture below have same Sid (are same users).
As you can see, attributes for class Member are empty. 
Attributes for class User have value. 

![image](https://user-images.githubusercontent.com/14541273/90984808-cc51c000-e577-11ea-8247-d5ef055a253d.png)

I would expect that attributes for these two classes would be same.

It does not matter if I get Member reference from Message or Channel. 
Attributes always return emtpy dict. 

`Attributes test3 = channel.getMembers().getMember(message.getAuthor()).getAttributes();`

**Comment by Gray-Wind** [comment]
Member and user are separate entities. Member is per-channel entity, you might want have different attributes across different channels for the same user, but users are unique for a given service instance.
