### ISSUE TITLE
Broadcast Functionality

### ISSUE THREAD

**Issue by rooparsh** [twilio/twilio-chat-demo-android#149]
We have a functionality in app wherein we can send a message to multiple users to multiple channels (They are not part of same channel and the project requirement doesn't allow us to add users to same channel).

1. Is there any way we can send same message to multiple channels at the same time. The message can be media or simple text message. 
2. And for the media message is there any way we upload the media once and reuse the link for other messages instead of uploading same media again and again.

**Comment by berkus** [comment]
1. You can call sendMessage in each channel where you want to send the message to.
2. No, not at the moment.

**Comment by rooparsh** [comment]
@berkus Won't it be time costly operation, looping through all the channels and sending them one by one. Also we have restrictions of 30 APS.

Any plan to include in the near future ?

**Comment by berkus** [comment]
@rooparsh no, this functionality is not supported by the backend.
