### ISSUE TITLE
twilio couldn't keep the volume to  the minimum during the call

### ISSUE THREAD

**Issue by hxlgithub** [twilio/twilio-chat-demo-android#15]
when the phone during the call,the sound could not be turn off in the android demo and twilio apk .
what is the reason of this phenomenon？
if i want to twilio can turn off  , how should i do?

**Comment by berkus** [comment]
The chat application does not use any voice/audio features, are you sure you're writing to the right repo?

**Comment by berkus** [comment]
Closing this as there was no response.
