### ISSUE TITLE
SDK release section is outdated and not relevant in this repo

### ISSUE THREAD

**Issue by emartynov** [twilio/twilio-chat-demo-android#151]
Subj

**Comment by berkus** [comment]
Seems matching to me: app depends on 5.0.1 and so it states in the README as well.

Please be more specific what is not correct?

**Comment by emartynov** [comment]
<img width="422" alt="Screenshot 2020-10-26 at 12 20 19" src="https://user-images.githubusercontent.com/295424/97166539-b5049e00-1785-11eb-8211-dc5771306dd8.png">

**Comment by berkus** [comment]
That's based on tags. No other tags exist atm.

**Comment by berkus** [comment]
Updated.

**Comment by emartynov** [comment]
@berkus Why do you have tags named sdk if you tag just demo project?

**Comment by berkus** [comment]
Because this is versions of the Chat SDK, this app doesn't have it's own version.

**Comment by emartynov** [comment]
My understanding that releases section is used for release versions of this project (https://github.blog/2013-07-02-release-your-software/). So there should be tags for this app release versions, and not sdk version dependencies.

**Comment by berkus** [comment]
It is not an app. It's a building block for starting your own application using Twilio Chat SDK.

**Comment by emartynov** [comment]
Oke, that explains it now. Thank you!
