### ISSUE TITLE
Make contribution to the project easier

### ISSUE THREAD

**Issue by emartynov** [twilio/twilio-chat-demo-android#153]
I need to create a fake Firebase project to be able to compile the project. It would be great if Twilio has some temp project setup already.

**Comment by berkus** [comment]
Not likely to happen. This project is not a standalone application, it's a scaffolding for creating your own.

**Comment by emartynov** [comment]
Oke, then you likely will get conversation from me instead of the contribution.

**Comment by berkus** [comment]
I do not see any relation between these two things, though.

Creating a firebase project and downloading a google-services.json is a step you'd need to do anyway.

**Comment by emartynov** [comment]
Related to #154
