### ISSUE TITLE
Stop using this repo's tickets as gateway to the tickets for SDK

### ISSUE THREAD

**Issue by emartynov** [twilio/twilio-chat-demo-android#154]
Question: I was proposed to use tickets on this repo as tickets to SDK itself. Is it correct approach?

**Comment by berkus** [comment]
I am always wary when some undisclosed voices are proposing anything without revealing themselves. Proposed by whom?

**Comment by emartynov** [comment]
Devrel: Hey, the best way to give that kind of feedback is either via me, or by opening up a ticket on one of the same apps for the sdk you're working on. The second being the best option because we have the engineers for those SDKs looking at those issues constantly


Me: Oke, so contact support action (what I'm doing now) is the best
Thank you

Devrel: Best if you can open issues on the Github repository to get to them directly

**Comment by berkus** [comment]
Ok, the github issues on this repo are maintained as a courtesy to stay in touch with developers. They provide no guarantees, no SLAs, and no gateway to the actual SDK tickets.

If you want actual Twilio support you best use your TAM.
