### ISSUE TITLE
JCenter is shutting down on May 1st, 2021

### ISSUE THREAD

**Issue by HappyDr0id** [twilio/twilio-chat-demo-android#158]
Bintray is shutting down JCenter on May 1st and the Twilio Chat SDK is only available on this repository. So here is a warning for all of us to not be surprised on this date. Do you plan to distribute the SDK through Maven Central or Jitpack before the deadline?

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by berkus** [comment]
Hi, thank you for pinging, we are aware of this and are looking at available options. 

We’ll update with the news in official channels once the choice is made.

**Comment by berkus** [comment]
Currently we've decided to publish on mavenCentral() because it's the easiest change for Android devs; [Conversations SDK have been published](https://www.twilio.com/docs/conversations/android/changelog#conversations-131-mar-11-2020) there with Chat SDK to soon follow.

**Comment by berkus** [comment]
This is done.
