### ISSUE TITLE
EMS service could not authenticate/authorize ether provided customer fpa token or twilio rtd token, unable to set FPA token

### ISSUE THREAD

**Issue by arorashilpa** [twilio/twilio-chat-demo-android#16]
Hi there,
I am getting the following error while using the quick-start demo for Twilio chat on android:
EMS service could not authenticate/authorize ether provided customer fpa token or twilio rtd token, unable to set FPA token

Can you pls help me to resolve this.

Thanks in advance.

**Comment by berkus** [comment]
Please check that you are using a correct accound and instance SID, and they are properly specified in your generated token.
