### ISSUE TITLE
APK size increases to 1.4 GB after integrating Programmable Chat

### ISSUE THREAD

**Issue by sushant-bizbrolly** [twilio/twilio-chat-demo-android#160]
### Description

After adding implementation of Twilio Programmable Chat in my build.gradle file, the generated debug APK size increased to 1.4 GB.
I introspected APK, and found the lib folder contains 4 folders with Twilio files in it. It all together took 1.4 GB.
Pleasehelp me out with this issue and how to resolve this.

### Steps to Reproduce

1. Add Twilio Programmable Chat implementation in build.gradle
2. Rebuild the project
3. Generate debug APK
4. And the size would be in GBs

#### Code (optional)

```kotlin
implementation 'com.twilio:chat-android-with-symbols:6.1.1'
```
#### Chat Android SDK

Which SDK version did you use? [eg. 2.0.8]
6.1.1

Screenshots attached.
![Screenshot from 2021-02-26 00-14-34](https://user-images.githubusercontent.com/77480199/109202284-d2478880-77c8-11eb-9cb7-865f15544078.png)
![Screenshot from 2021-02-26 00-16-12](https://user-images.githubusercontent.com/77480199/109202289-d378b580-77c8-11eb-8091-0fc31c5516fd.png)
![Screenshot from 2021-02-26 00-17-17](https://user-images.githubusercontent.com/77480199/109202294-d378b580-77c8-11eb-8845-ae7006e3c1b2.png)
![Screenshot from 2021-02-26 00-19-04](https://user-images.githubusercontent.com/77480199/109202296-d4114c00-77c8-11eb-82cd-aa8c7a52c879.png)
![Screenshot from 2021-02-26 00-19-53](https://user-images.githubusercontent.com/77480199/109202297-d4a9e280-77c8-11eb-89f2-c597ff6494c3.png)
![Screenshot from 2021-02-26 00-21-26](https://user-images.githubusercontent.com/77480199/109202300-d5427900-77c8-11eb-80a7-d319257d62de.png)
![Screenshot from 2021-02-26 00-21-52](https://user-images.githubusercontent.com/77480199/109202303-d5db0f80-77c8-11eb-865a-0c46dc84f30b.png)
![Screenshot from 2021-02-26 00-22-11](https://user-images.githubusercontent.com/77480199/109202305-d5db0f80-77c8-11eb-9ff5-9ba8d90a005d.png)
![Screenshot from 2021-02-26 00-22-55](https://user-images.githubusercontent.com/77480199/109202306-d673a600-77c8-11eb-9931-c7ac0df5a3a4.png)

**Comment by berkus** [comment]
Do you have NDK  installed? if you use `implementation 'com.twilio:chat-android-with-symbols:6.1.1'`  then you need NDK installed to strip out the debug symbols after the build.

Try with `implementation 'com.twilio:chat-android:6.1.1'` instead first (this will not give you debug info, but the APK should definitely be smaller), then install NDK if you actually require debug symbols.

**Comment by sushant-bizbrolly** [comment]
Ok thanks, I will try out this solution of yours and let you know if any issues faced further.

**Comment by berkus** [comment]
@sushant-bizbrolly hi, did you make it work?  need any more help?

**Comment by sushant-bizbrolly** [comment]
@berkus yeah, it worked. thanks. I am using the without symbols integration, and the APK size is around 35MB.
Thanks for the help.

**Comment by berkus** [comment]
Glad to hear it! Cheers!
