### ISSUE TITLE
Sample JSON missing

### ISSUE THREAD

**Issue by mahendran90** [twilio/twilio-chat-demo-android#162]
I am trying to integrate the sample chat bot application in android studio which is state me like this: 

Please help us to resolve it..
 
File google-services.json is missing. The Google Services Plugin cannot function without it.

**Comment by berkus** [comment]
Yes, you need to download this  file from YOUR firebase console. [See here](https://github.com/twilio/twilio-chat-demo-android#add-google-servicesjson).
