### ISSUE TITLE
Connection Status 

### ISSUE THREAD

**Issue by luish000** [twilio/twilio-chat-demo-android#2]
Hi people, I have a problem :( 

I need to know if the web socket connection with twilio server is lost...

**Comment by berkus** [comment]
You will get this notification from the client `onConnectionStateChanged` call back. [For example, like here](https://github.com/twilio/twilio-chat-demo-android/blob/9a2180c80e3a5b55a060225d8b194a6d2479ff32/chat-demo-android/src/main/java/com/twilio/chat/demo/ChannelActivity.java#L469)

It usually takes about 30 seconds for twilsock to give up and indicate that it's no longer connected.

**Comment by berkus** [comment]
Fell free to reopen this if you have further questions.
