### ISSUE TITLE
Not able to invite member to channel

### ISSUE THREAD

**Issue by arorashilpa** [twilio/twilio-chat-demo-android#20]
error - 50107/50200 is coming.
Pls help

**Comment by berkus** [comment]
Does your user have channelAdmin permission?

**Comment by berkus** [comment]
50107 is User is not authorized
50200 is User not found

https://www.twilio.com/docs/api/errors#5-anchor

**Comment by arorashilpa** [comment]
Does your user have channelAdmin permission?

- yes

**Comment by arorashilpa** [comment]
its still giving error. -_-

**Comment by berkus** [comment]
Well, if you want some more specific answers we'd need your Account SID, and some logs from the client.

How did you create the user you're trying to invite?

**Comment by arorashilpa** [comment]
Hi berkus,

Acc SID - AC2a0616520848f859dc6fdc065b7ef759
and I am trying to invite user via user_id that was created from backend.

**Comment by arorashilpa** [comment]
Okay, so the thing is. I have two android apps - customer and admin app.
when I am trying to communicate between two users of customer app : then its working fine.
but when I am trying to do the same within customer and admin app. it says the user is not authorized.
although I using the same integration in both the apps.

**Comment by berkus** [comment]
Have you checked the role permissions of the admin user?

**Comment by arorashilpa** [comment]
Hey Berkus. Thanks a lot. Issue got resoved. there was some error regarding the token generation. 
BTW, I need your help in one more topic.
Like if i invite some user on a particular channel that how do that user come to know? i want some popup/notification to show to that user on any screen. is that possible? :|

**Comment by berkus** [comment]
You will get onChannelJoined or onChannelInvited event and can construct and show a popup notification in the handler for it.

There's also push notification for that - you can enable push notifications and use handler similar to [this](https://github.com/twilio/twilio-chat-demo-android/blob/master/chat-demo-android/src/main/java/com/twilio/chat/demo/services/FCMListenerService.kt#L46) to show notification.

**Comment by arorashilpa** [comment]
> You will get onChannelJoined or onChannelInvited event and can construct and show a popup notification in the handler for it

I want this in any of the screen^^

**Comment by berkus** [comment]
Use the code I linked to to construct a notification and show it.

**Comment by arorashilpa** [comment]
FOr this^ do we have to enable push notification on Twilio Console?

**Comment by berkus** [comment]
If you listen for the ChatClientListener.onChannelJoined and onChannelInvited then you do not. If you use push notifications then yes.

**Comment by arorashilpa** [comment]
how to listen for those events? Can you please elaborate a lit bit ?

**Comment by arorashilpa** [comment]
> You will get onChannelJoined or onChannelInvited event and can construct and show a popup notification in the handler for it

This will show only on one same Chat screen right? Not on other screens? :(

**Comment by berkus** [comment]
Do you add a listener to ChatClient? In that listener you will receive those events.

See https://media.twiliocdn.com/sdk/android/chat/releases/2.0.0/docs/com/twilio/chat/ChatClientListener.html#onChannelInvited-com.twilio.chat.Channel-

**Comment by arorashilpa** [comment]
Yes already added!! I am already handling those events.

I am really confused about how to get notification/popup on any activity of the APP so that the other user will come to know that he is being invited to one channel by someone.

**Comment by arorashilpa** [comment]
I am using the source code from this link:
https://github.com/TwilioDevEd/chat-quickstart-android/archive/master.zip.

**Comment by berkus** [comment]
You should try the demo application, which handles the Invite events - https://github.com/twilio/twilio-chat-demo-android/

**Comment by berkus** [comment]
In the callbacks you're free to show a dialog, or, if you don't want to break the app flow, create a notification and show it using standard android notification area.

**Comment by arorashilpa** [comment]
> You should try the demo application, which handles the Invite events - https://github.com/twilio/twilio-chat-demo-android/

this is in Kotlin :/. I need that it proper java-android

**Comment by berkus** [comment]
You can try this for java version https://github.com/twilio/twilio-chat-demo-android/tree/sdk-1.0.9

**Comment by berkus** [comment]
Any updates?

**Comment by berkus** [comment]
Closing as there is no response. Reopen when you have new update.
