### ISSUE TITLE
[Question] Programmable Chat on Xamarin

### ISSUE THREAD

**Issue by alberk8** [twilio/twilio-chat-demo-android#21]
Is there any plan to support Twilio Programmable Chat in Xamarin?  Thank you.

**Comment by berkus** [comment]
Yes, it's in the works.

**Comment by alberk8** [comment]
Thanks for the reply.  
1) May I know when is the likely timeframe for a public release?
2) Will there be support for Xamarin Forms besides Xamarin Android and Xamarin IOS?

**Comment by berkus** [comment]
1. Not sure about the public release date, it's only getting it's ios part finished (android works); probably we will do a beta q1 2018.
2. Not at this point, again only afaik.

**Comment by alberk8** [comment]
Hi,
Thanks for the update.  Please keep me update.  It is possible for us to test the Android Beta. We are at a stage where we are ready to take on the Chat portion of our Xamarin App.

**Comment by berkus** [comment]
Ok, I will post with more information next week.

**Comment by cloudjubei** [comment]
Is there any update on this?
Also, is there anyone working on getting the Twilio Video to work on Xamarin (iOS + Android) ?

**Comment by dkornev** [comment]
@cloudjubei I packed a nuget 1.3.1 of Twilio.Video for IOS. https://github.com/dkornev/TwilioXamarinBindings which is pretty stable even for prod.
Don't think that they will support Xamarin soon

**Comment by berkus** [comment]
@cloudjubei yes, we have released official Xamarin support, please take a look [here](https://github.com/twilio/TwilioChatXamarinBindings).

**Comment by dkornev** [comment]
@berkus Absolutely good news. But are you planing to support Xamarin.Video and Xamarin.Voice the same way soon?

**Comment by berkus** [comment]
@dkornev as far as I know, no, so your implementation is good to go unofficially :)

**Comment by Doughouzlight** [comment]
@dkornev can you please check your email regarding your library

**Comment by murugeshv** [comment]
Hi Twilio Team, 
I am expecting your valuable guidance or help. My know is it possible to integrate twilio chat in Xamarin forms (Not in shared project in Xamarin) ?.   If yes, I need sample  projects or xamarin forms Twilio chat integration document. 

And one more question when I install the Twilio.Chat.Xamarin 0.4.1 in Xamarin forms , I got error . i think it seems Twilio not support in xamarin forms.
Error	NU1202	Package Twilio.Chat.Xamarin 0.4.1 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package Twilio.Chat.Xamarin 0.4.1 supports:
  - monoandroid44 (MonoAndroid,Version=v4.4)
  - xamarinios (Xamarin.iOS,Version=v0.0)

**Comment by aleksandrsivanovs** [comment]
Hi!

Unfortunately, moving to .NET 2.0 standard for our Xamarin bindings is not in our current plans for this year. 

Aleksandrs
