### ISSUE TITLE
Make it work with minsdk 16

### ISSUE THREAD

**Issue by rohitlien** [twilio/twilio-chat-demo-android#24]
How to make it work with minsdk 16 instead of 19

**Comment by berkus** [comment]
You have to specify sdk version override in AndroidManifest.xml.

The way to override the SDK level is like this:

```
<uses-sdk
     android:minSdkVersion="14"
     android:targetSdkVersion="23"
     tools:overrideLibrary="com.twilio.chat"
     />
```

**Comment by berkus** [comment]
Closing, please reopen if you have further questions.
