### ISSUE TITLE
No implementation found for com.twilio.chat.Messages com.twilio.chat.Channel.getMessages

### ISSUE THREAD

**Issue by kbagchiGWC** [twilio/twilio-chat-demo-android#25]
@marcoRS  mistakenly open the issue in https://github.com/twilio/twilio-client-quickstart-android.
```
implementation 'com.twilio:chat-android:0.12.2'
implementation 'com.twilio:accessmanager-android:0.1.0'
```

We are seeing the following error in our app:

```
Caused by java.lang.UnsatisfiedLinkError: 
No implementation found for com.twilio.chat.Messages com.twilio.chat.Channel.getMessages() (tried Java_com_twilio_chat_Channel_getMessages and Java_com_twilio_chat_Channel_getMessages__) at com.twilio.chat.Channel.getMessages(Channel.java)
```

This seems to be a native error but we are unsure on how to proceed to fix this.

**Comment by berkus** [comment]
0.12.2 is very ancient and is not effectively supported, please upgrade to 1.0.11 or 2.0.2.

**Comment by berkus** [comment]
Closing, please reopen if you have further questions.
