### ISSUE TITLE
Black screen coming after pressed on login button

### ISSUE THREAD

**Issue by ajitdubey-mob-ibtech** [twilio/twilio-chat-demo-android#3]
I have setup your ip messaging code in our Android Studio IDE after that created google-services.json file from google portal. When I am going to click on login button application going to stuck with black screen and found some log given below.

07-21 16:27:30.289 352-352/com.twilio.ipmessaging.demo.debug D/TwilioAccessManagerObserver(native): onTokenUpdated.
07-21 16:27:30.304 352-352/com.twilio.ipmessaging.demo.debug D/IPMessagingClient(native): Creating notification client
07-21 16:27:30.309 352-352/com.twilio.ipmessaging.demo.debug D/IPMessagingClient(native): Creating client with init strategy ChannelLists
07-21 16:27:30.329 352-658/com.twilio.ipmessaging.demo.debug D/IPMessagingClientListener(native): onClientSynchronization
07-21 16:27:30.334 352-665/com.twilio.ipmessaging.demo.debug D/IPMessagingClientListener(native): onToastSubscribed

07-21 16:27:30.359 352-658/com.twilio.ipmessaging.demo.debug E/BasicIPMessagingClient: Received onClientSynchronization callback with status STARTED
07-21 16:27:30.364 352-666/com.twilio.ipmessaging.demo.debug I/BasicIPMessagingClient: GCM registration successful
07-21 16:27:30.474 352-352/com.twilio.ipmessaging.demo.debug W/IPMessagingClient(native): Messaging lib not ready, retrying...

07-21 16:27:31.634 352-694/com.twilio.ipmessaging.demo.debug E/TwilioApplication: Received onError event. Error code: 8, text: Provided grant token is not authentic or has expired

07-21 16:27:31.644 352-695/com.twilio.ipmessaging.demo.debug E/ChannelActivity: Received onClientSynchronization callback FAILED
07-21 16:27:31.989 352-666/com.twilio.ipmessaging.demo.debug E/TwilioApplication: GCM registration not successful. Error code: 5, text: Notification exception during registration: TNException: Couldn't create registration

Please support us what is the problem behind that. You support more appreciable.

Thanks,
Ajit
Thanks,

**Comment by Xiaoning1943** [comment]
Hello, I have the same issue. After login success,  the black screen happened when launching ChannelActivity. 
Log:
08-20 17:32:18.077 E/DynamiteModule(29470): Failed to load module descriptor class: Didn't find class "com.google.android.gms.dynamite.descriptors.com.google.firebase.auth.ModuleDescriptor" on path: DexPathList[[zip file "/data/app/com.twilio.ipmessaging.demo.debug-2/base.apk"],nativeLibraryDirectories=[/data/app/com.twilio.ipmessaging.demo.debug-2/lib/arm, /vendor/lib, /system/lib]]

Thanks,
Shilry

**Comment by bradbumbalough** [comment]
I'm having the same issue in iOS.. were you able to get it resolved?

**Comment by bradbumbalough** [comment]
I was able to get this working by not using the test token from the Debugger tools, but instead generate from from my server.

**Comment by ajitdubey-mob-ibtech** [comment]
Now it's working fine with Programmable Chat Android v0.11 and Programmable Chat iOS 0.16.0.

**Comment by berkus** [comment]
> Provided grant token is not authentic or has expired

Your token was invalid or expired, how are you generating it?

**Comment by berkus** [comment]
Feel free to reopen this if you have further questions.

**Comment by ajitdubey-mob-ibtech** [comment]
Now it's working fine.
Thanks for your support

**Comment by Batiskaf** [comment]
> Provided grant token is not authentic or has expired

Having this error while using react-native-twilio-chat even though the token was verified in jwt.io

**Comment by berkus** [comment]
I guess [TwilioChatJsReactNative](https://github.com/twilio/TwilioChatJsReactNative) is the best place to report this!
