### ISSUE TITLE
Chat Demo App-JAVA Version

### ISSUE THREAD

**Issue by AdnanSattar** [twilio/twilio-chat-demo-android#30]
hi there, can you upload java version of demo chat along with Kotlin?

**Comment by q296789611** [comment]
I think so too. Don't understand the Kotlin

**Comment by berkus** [comment]
Yes, it's still available [here](https://github.com/twilio/twilio-chat-demo-android/tree/java)

I will push updates for 2.x sdk, but they are minor and should be easy.
