### ISSUE TITLE
App crash on login

### ISSUE THREAD

**Issue by ShrikantBadwaik-007** [twilio/twilio-chat-demo-android#32]
I'm getting an issue where app is getting crashed on clicking "LogIn" button.
After debugging, I found out that responseCode is 404 instead of 200 I don't know why.

As specified in docs, I followed steps in [Building](https://github.com/twilio/twilio-chat-demo-android/tree/java#building) section.

I'm running this demo on Genymotion.

Please help, Thanks.

**Comment by berkus** [comment]
Did you configure the ACCESS_TOKEN_SERVICE_URL value to your service URL?
404 means your URL is not found.

**Comment by ShrikantBadwaik-007** [comment]
Yes, I have configured ACCESS_TOKEN_SERVICE_URL. I tried by adding the value in gradle.properties(which was not present previously so created new one), then by replacing ACCESS_TOKEN_SERVICE_URL in LoginActivity by "http://example.com/get-token". But nothing worked.

Also, what do you mean by **your service URL**. I'm using this url: http://example.com/get-token.

**Comment by berkus** [comment]
I mean the service that you have written and use to provide tokens to properly authenticated users as described [here](https://www.twilio.com/docs/api/rest/access-tokens).

**Comment by berkus** [comment]
Closing this, feel free to reopen if you still have issues.

**Comment by gergovOT** [comment]
So we have to create the server on our own? I don't really understand it, not even reading <a href="https://www.twilio.com/docs/api/chat/guides/identity" rel="nofollow">this</a> and <a href="https://www.twilio.com/docs/api/rest/access-tokens" rel="nofollow">this</a>. Where am i supposed to write this code? And how to connect it with gradle.properties. Sorry for the question i am just a beginner.

**Comment by InI4** [comment]
@gergovOT as I understand, this is a security feature, generating a (temporary) token on your own remote server avoids exposing any secrets on your client.

**Comment by berkus** [comment]
@gergovOT yes, you have to write the server for authenticating your users. Chat use scenarios assume you have some **backend** which lets you know which user is which and let them **log in** into the service.

[The document you linked first](https://www.twilio.com/docs/api/chat/guides/identity) says this in the very first paragraph:

**you will be responsible for two components:
...
A server which vouches for the identity of your users**

it then goes on to describe what such Server should implement in the following paragraphs.

[The second document you linked](https://www.twilio.com/docs/api/rest/access-tokens) says in the very first paragraph:

**You create them on your server to verify a client's identity and grant access to client API features.**

it then goes on to describe how to produce a token in a minute detail.

**Comment by gergovOT** [comment]
@berkus Is there a tutorial for Kotlin? Because i didn't find such anywhere.

**Comment by berkus** [comment]
Do you mean [the Kotlin tutorials](https://kotlinlang.org/docs/tutorials/)?

**Comment by gergovOT** [comment]
I mean the implementation of AccessToken. When I import this 
import com.twilio.jwt.accesstoken.AccessToken;
import com.twilio.jwt.accesstoken.VoiceGrant;
i get the following error "Unresolved reference: jwt". Am I missing something?

**Comment by gergovOT** [comment]
I can not really synchronize Kotlin and twilio library

**Comment by berkus** [comment]
I don't know. Is this related to the Twilio Chat SDK? These classes are definitely not part of the SDK.

Probably you want to import some other packages for these.

**Comment by gergovOT** [comment]
It is imported in the tutorial you have sent me. You can see it in the first block of code right <a href="https://www.twilio.com/docs/api/rest/access-tokens#creating-tokens" rel="nofollow">here</a>

**Comment by berkus** [comment]
This is documentation for REST API, not for Chat SDK.

If you click the github button just above the code sample you will see the necessary imports for that piece of code:

1. Go to https://github.com/TwilioDevEd/api-snippets
2. Read the installation instructions, note `ruby tools/snippet-testing/model/dependency.rb`
3. [Look at java dependencies in that file](https://github.com/TwilioDevEd/api-snippets/blob/master/tools/snippet-testing/model/dependency.rb#L24)
4. Add those to your gradle script, [here](https://github.com/twilio/twilio-chat-demo-android/blob/master/chat-demo-android/build.gradle#L21)
