### ISSUE TITLE
Error while setting token

### ISSUE THREAD

**Issue by ShrikantBadwaik-007** [twilio/twilio-chat-demo-android#33]
Hi, I getting this issue while creating ChatClient **"Operation has been canceled. Unable to set FPA token."**

this is the token response I'm getting from my server.
`{"token":"eyJhbGciOiJIUzI1NiIsImN0eSI6InR3aWxpby1mcGE7dj0xIiwidHlwIjoiSldUIn0.eyJqdGkiOiJTS2VjNTc2Y2MzOTMxYTYwY2JiNTM2OTFlMzNiZWFiNTY3LTE1MTk2NDE0NDYiLCJncmFudHMiOnsiaWRlbnRpdHkiOjIsImNoYXQiOnsic2VydmljZV9zaWQiOiJJUzM4ZmVlYWM2YzllMTQ2NGRhNzBjODBhN2FkYTU1OTBmIn19LCJpc3MiOiJTS2VjNTc2Y2MzOTMxYTYwY2JiNTM2OTFlMzNiZWFiNTY3IiwibmJmIjoxNTE5NjQxNDQ2LCJleHAiOjE1MTk2NDUwNDYsInN1YiI6IkFDMjNkYzJlZjY0OTM3ZDJmN2Q2NDZiMDEyYzdmZTQ0ODEifQ.vtpG9tfW1ofzgeV7Uo7HD6KwTxtVwyKRE6rJ4D8buag"}`

Once I got token I'm initializing AccessManager & ChatClient as
AccessManager:
```
private void createAccessManager() {
        if (accessManager != null) return;

        accessManager = new AccessManager(accessToken, new AccessManager.Listener() {
            @Override
            public void onTokenWillExpire(AccessManager accessManager) {

            }

            @Override
            public void onTokenExpired(AccessManager accessManager) {
                createToken();
            }

            @Override
            public void onError(AccessManager accessManager, String errorMessage) {
                if (callback != null) callback.onError(errorMessage);
            }
        });

        accessManager.addTokenUpdateListener(token -> {
            if (chatClient == null) return;

            chatClient.updateToken(token, new StatusListener() {
                @Override
                public void onSuccess() {
                    if (DEBUG) Log.d(TAG, "Token updated successfully.");
                }

                @Override
                public void onError(ErrorInfo errorInfo) {
                    if (callback != null) callback.onError(errorInfo.getMessage());
                }
            });
        });
    }
```
ChatClient:
```
private void createChatClient() {
        if (chatClient != null) return;

        ChatClient.Properties properties = new ChatClient.Properties.Builder()
                .setRegion("us1")
                .createProperties();
        ChatClient.create(context, accessToken, properties, this);
    }
```

This is the implementation for CallbackListener:
```
@Override
    public void onSuccess(ChatClient chatClient) {
        AppUtil.debugLog(TAG, "ChatClient initialized");
        this.chatClient = chatClient;
        if (callback != null) callback.onSuccess(null);
    }

    @Override
    public void onError(ErrorInfo errorInfo) {
         if (callback != null) callback.onError(errorInfo.getMessage());
    }
```

Please help. Thanks.

**Comment by berkus** [comment]
One thing i noted is you’re using numerical identities. Try something like “s2” instead of just 2. 
Also, please do not post tokens in the open. Use ticketing system on support.twilio.com to open a support ticket and post private information there.

**Comment by ShrikantBadwaik-007** [comment]
I didn't understood what you are trying to say. But sometimes my client gets initialized without giving mentioned error and sometimes it didn't giving mentioned error.

**Comment by berkus** [comment]
You have `"identity": 2` in your token. Best way to ensure identity will be a string is to use some letters in it.

**Comment by ShrikantBadwaik-007** [comment]
I don't know might be issue with internet connectivity. Because I'm getting the error when slow internet connectivity.

**Comment by berkus** [comment]
Unstable internet connectivity could be an issue, too.
