### ISSUE TITLE
getUnconsumedMessagesCount not relevant data issue

### ISSUE THREAD

**Issue by DummyCo** [twilio/twilio-chat-demo-android#39]
Hi there! Seems like trying to acquire unconsumed messages count in _onMessageAdded()_ callback results in not relevant data from time to time.

### Steps to Reproduce

1. Get _onMessageAdded()_ callback
2. Request _getUnconsumedMessagesCount()_ for channel in that callback

#### Code (optional)

```
    @Override
    public void onMessageAdded(Message message) {
        Log.d(TAG, "onMessageAdded() called with: message = [" + message + "]");
        fetchUnconsumedMessagesCount(message.getChannel());
    }
```

Where _fetchUnconsumedMessagesCount()_ delegates to:

```
    private void fetchUnconsumedMessagesCount(Channel channel) {
        channel.getUnconsumedMessagesCount(
                new CallbackListener<Long>() {
                    @Override
                    public void onSuccess(Long aLong) {
                        deliverUnconsumedMessagesCount(channel, aLong);
                    }
                }
        );
    }
```

#### Expected Behavior

Acquire relevant unconsumed messages count

#### Actual Behavior

Old, not relevant data from time to time

#### Chat Android SDK

2.0.8

#### Android API

27

#### Android Device

Nexus 5X
Pixel XL

**Comment by berkus** [comment]
Please collect logs as described [here](https://github.com/twilio/twilio-chat-demo-android/blob/master/REPORT_BUGS.md). Full unedited logs help reproduce and fix issues faster.

> Old, not relevant data 

Remember that chat library has a cache period, and if you call these functions too fast they will often return previous cached results (i.e. do not request more often than once in 5 seconds - the data will not be updated).

**Comment by DummyCo** [comment]
@berkus will collect logs ASAP, but

> Remember that chat library has a cache period, and if you call these functions too fast they will often return previous cached results (i.e. do not request more often than once in 5 seconds - the data will not be updated).

In that case how is it possible to get reliable number of unconsumed messages for channel at any moment then?
For instance that's obvious intent to update unconsumed messages counter for chat rooms list in realtime together with last message preview, but regarding current issues we're getting relevant last message and not relevant unconsumed messages count.
It's possible to implement appropriate pipelines with messages caching and read state preserving to count unconsumed messages on client code side but I think there should be a reliable way to perform that on SDK side.

**Comment by DummyCo** [comment]
It's still being an actual issue btw.
Just check out the behavior:

```
11:09:12.439 D/ChatManager: onTypingStarted() called with: member = [com.twilio.chat.Member@2017abc]
11:09:12.750 D/ChatManager: onTypingEnded() called with: member = [com.twilio.chat.Member@2017abc]
11:09:12.751 D/ChatManager: onMessageAdded() called with: message = [com.twilio.chat.Message@5b379ab]
11:09:13.111 D/ChatManager: User attributes set
11:09:13.356 D/ChatManager: onTypingStarted() called with: member = [com.twilio.chat.Member@2017abc]
11:09:13.658 D/ChatManager: onMemberUpdated() called with: member = [com.twilio.chat.Member@2017abc], updateReason = [LAST_CONSUMED_MESSAGE_INDEX]
11:09:15.540 D/ChatManager: onTypingEnded() called with: member = [com.twilio.chat.Member@2017abc]
11:09:15.540 D/ChatManager: onMessageAdded() called with: message = [com.twilio.chat.Message@ed7298b]
11:09:15.815 D/ChatManager: onMemberUpdated() called with: member = [com.twilio.chat.Member@2017abc], updateReason = [LAST_CONSUMED_MESSAGE_INDEX]
11:09:15.936 D/ChatManager: User attributes set
11:09:19.499 D/ChatManager: onTypingStarted() called with: member = [com.twilio.chat.Member@2017abc]
11:09:20.121 D/ChatManager: onTypingEnded() called with: member = [com.twilio.chat.Member@2017abc]
11:09:20.123 D/ChatManager: onMessageAdded() called with: message = [com.twilio.chat.Message@fe8874f]
11:09:20.743 D/ChatManager: User attributes set
11:09:21.035 D/ChatManager: onMemberUpdated() called with: member = [com.twilio.chat.Member@2017abc], updateReason = [LAST_CONSUMED_MESSAGE_INDEX]
```
I'm sending 3 messages to channel with time interval in couple of seconds and from time to time there is no _LAST_CONSUMED_MESSAGE_INDEX_ update happening like between these timestamps:
```
11:09:20.123
11:09:20.743
```

**Comment by a-rank** [comment]
Hey, Allan from Programmable Chat team here. 

onMemberUpdated() callback with reason updateReason = [LAST_CONSUMED_MESSAGE_INDEX] happens when corresponding member updates their consumption index, it is not connected to receiving new message in a channel. Consumption update is something that is not done automatically by Chat SDK, but rather by a developer via explicit call: 

```
public void setLastConsumedMessageIndexWithResult(long lastConsumedMessageIndex,
                                                  CallbackListener<java.lang.Long> listener)
```

https://media.twiliocdn.com/sdk/android/chat/releases/2.0.8/docs/com/twilio/chat/Messages.html#setLastConsumedMessageIndexWithResult-long-com.twilio.chat.CallbackListener-

**Comment by DummyCo** [comment]
Hey, @a-rank! I see, my description fault.
But at the same time I'm trying to fetch unconsumed messages count with _channel.getUnconsumedMessagesCount()_ method in _onMessageAdded()_ callback and getting not relevant result from time to time. Is there a way to get relevant unconsumed messages count while acquiring new message callback? That's the point.
Thank you!

**Comment by a-rank** [comment]
Chat SDK currently caches results for 5 seconds which may be too long of a period for getting more-or-less-real-time results. We are experimenting with lowering cache timeout limit, this change will be a service-side one and would not require a SDK update from your side. Will let you know when it will be deployed to production.

**Comment by berkus** [comment]
Hi, this should be in production already.

Please measure and reopen this if you still have issues.

**Comment by shrishailcne** [comment]
I am running the same code whatever given in twilio android docs . But channel manger is null while calling in other activity.

**Comment by shrishailcne** [comment]
channelsObject = chatClientManager.getChatClient().getChannels();
i am getting null here.

**Comment by berkus** [comment]
@shrishailcne could you please open another ticket? Your issue does not seem relevant to the current one.

**Comment by satyambhatt** [comment]
how to get unread messages count from twilio in javascript as per channel

**Comment by berkus** [comment]
@satyambhatt [docs](https://media.twiliocdn.com/sdk/js/chat/releases/3.2.3/docs/Channel.html#getUnconsumedMessagesCount__anchor)

**Comment by satyambhatt** [comment]
how to consume all unconsumed message  in twilio in javascript

**Comment by berkus** [comment]
@satyambhatt [docs](https://media.twiliocdn.com/sdk/js/chat/releases/3.2.3/docs/Channel.html#setAllMessagesConsumed__anchor)
