### ISSUE TITLE
Can not resolve symbol gcm_defaultSenderId

### ISSUE THREAD

**Issue by ajitdubey-mob-ibtech** [twilio/twilio-chat-demo-android#4]
After building application in android studio found error. Please let me know what will be the actual value.
What will be the actual value Project Id or Project number.

Thanks,
Ajit

**Comment by berkus** [comment]
This value comes from google-services.json file, generate one in Google Console and add it to the project (put it in chat-demo-android/ folder).

**Comment by berkus** [comment]
Fell free to reopen this if you have further questions.
