### ISSUE TITLE
Deadlock in 2.0.8 causes ANR

### ISSUE THREAD

**Issue by InI4** [twilio/twilio-chat-demo-android#40]
> Before filing an issue please check that the issue is not already addressed by the following:
>  * [Github Issues](https://github.com/twilio/twilio-chat-demo-android/issues)
>  * [Changelog](https://www.twilio.com/docs/api/chat/changelogs/android)

### Description

[Description of the issue]

### Steps to Reproduce

1. User installs widget to app. Widgets needs application object also containing Twilio stack.
2. User observes ANR between app and widget running in background

#### Expected Behavior

no lock

#### Actual Behavior

lock, ANR

#### Reproduces how Often

seems to happens once a day on that users device

#### Logs

I have this stack trace from Google Play
```
"main" prio=5 tid=1 Native
  | group="main" sCount=1 dsCount=0 obj=0x761afea0 self=0x7632c96a00
  | sysTid=10981 nice=0 cgrp=default sched=0/0 handle=0x7636adda98
  | state=S schedstat=( 42154351301 10675283465 52491 ) utm=3670 stm=544 core=1 HZ=100
  | stack=0x7fc238f000-0x7fc2391000 stackSize=8MB
  | held mutexes=
 
  #00  pc 000000000001ad44  /system/lib64/libc.so (syscall+28)
 
  #01  pc 0000000000067e00  /system/lib64/libc.so (pthread_cond_wait+96)
 
  #02  pc 000000000070b0a0  /data/app/de.spieleck.app.badgers-1/lib/arm64/libtwilio-rtd-native.so (???)
 
  #03  pc 00000000003a8e54  /data/app/de.spieleck.app.badgers-1/lib/arm64/libtwilio-rtd-native.so (Java_com_twilio_chat_ChatClient_nativeUpdateToken+472)
 
  #04  pc 00000000000478b0  /data/app/de.spieleck.app.badgers-1/oat/arm64/base.odex (Java_com_twilio_chat_ChatClient_nativeUpdateToken__Ljava_lang_String_2JLcom_twilio_chat_StatusListener_2+188)
 
  at com.twilio.chat.ChatClient.nativeUpdateToken (ChatClient.java)
 
  at com.twilio.chat.ChatClient.updateToken (ChatClient.java:371)
- locked <0x00e0e959> (a com.twilio.chat.ChatClient)
 
  at de.spieleck.app.badgers.chat.twilio.BasicChatClient.onTokenUpdated (BasicChatClient.java:304)
 
  at com.twilio.accessmanager.AccessManager.updateToken (AccessManager.java:82)
 
  at de.spieleck.app.badgers.chat.twilio.BasicChatClient$GetAccessTokenAsyncTask.onPostExecute$552c4e01 (BasicChatClient.java:196)
  or                     .onPostExecute (BasicChatClient.java:196)

```

Or attach it as a file.

#### Chat Android SDK

2.0.8

#### Android API

7.1

#### Android Device

Motorola Moto Z

**Comment by berkus** [comment]
Please collect logs as described [here](https://github.com/twilio/twilio-chat-demo-android/blob/master/REPORT_BUGS.md). Full unedited logs help reproduce and fix issues faster.

**Comment by InI4** [comment]
As I cannot reproduce this on local devices or emulators, but it happens on a users one. Is there a best practise, how to collect Twilio logs on a users device?

**Comment by berkus** [comment]
Do you collect Crashlytics logs? I think they're able to save at least relevant part of the user's log for analysis.

This snippet is clearly not enough to identify the problem. If you could post your source code, please do so via private support.twilio.com ticket then I will be able to analyse and try to reproduce. Otherwise, only more detailed logs would help, preferably in DEBUG log level.

**Comment by InI4** [comment]
Hmm, will try to do better in the future, right now I do not have more information at hand.

**Comment by berkus** [comment]
No worries, thanks for the report - I will try to reproduce this but without exact code flow it might be hard - I suspect you're doing something out of the ordinary with the exposed SDK APIs.

**Comment by berkus** [comment]
No luck in reproducing this.

I will close this for now, but if you get a more reproducible case or better logs from crashlytics, don't hesitate to reopen.
