### ISSUE TITLE
Update Policies

### ISSUE THREAD

**Issue by InI4** [twilio/twilio-chat-demo-android#43]
### Description

This is no software bug!

I am just a bit puzzled. I was hoping for some better 2.0.X. Now I see there a bug report for 3.0.0. Quick check reveals, API has changed, so move is a bit more than just switching dependencies. Are there docs about new APIs? Will there be a 2.0.9? Is 3.0.0 for production? Google search ends on 404, where are instructive changelogs? What are planned steps for both APIs and Apps using it? 

Yea I know, this all requires work to be done, but it is really hard, to keep in touch without. 
Thank you for your time!

**Comment by berkus** [comment]
The changelogs are in their [usual place](https://www.twilio.com/docs/chat/android/android). The documentation is updated but it's in the [usual place](https://media.twiliocdn.com/sdk/android/chat/releases/3.0.0/docs/) as well.

According to semver, versions with changed major version include breaking changes so there shouldn't be any surprise either.

**Comment by InI4** [comment]
I get a 404 with the first link. 
And I never found that docs thing with google. Thanks, will have a look.

**Comment by berkus** [comment]
Fixed link - [it should be this](https://www.twilio.com/docs/chat/android/changelog)
