### ISSUE TITLE
channel.getMessages returns null.

### ISSUE THREAD

**Issue by aalap03** [twilio/twilio-chat-demo-android#49]
I saw the issue for the same on [SO but](https://stackoverflow.com/questions/40779198/getting-null-while-calling-for-messages-on-current-channel-in-twilio-chat-androi) the issue there was calling `channel.getMessages()` outside `onSuccess()` method but I am doing inside `onSuccess()` method and that also after checking `getMembersCount(), getMessagesCount() and getUnconsumedMessagesCount()` methods which all returns expected values.

Below is my code with step by step procedure from getting `chatClient` to `channelDescriptor` and then `channel`, please let me know what I am missing.

**Expected Behavior**
Get messages for the channel.

**Actual Behavior**
getMessages() method returns null even though there are messages.

**Reproduces how Often**
95%

    @Override
    public void onSuccess(ChatClient chatClient) {
        ArrayList<ChannelModelJ> channelGroups = new ArrayList<>();
        chatClient.setListener(this);

        chatClient.getChannels().getUserChannelsList(new CallbackListener<Paginator<ChannelDescriptor>>() {
            @Override
            public void onSuccess(Paginator<ChannelDescriptor> paginator) {
                for (ChannelDescriptor cd : paginator.getItems()) {
                    channels.put(cd.getSid(), new ChannelModelJ(cd));
                    testMessageMethod(cd); // this is for observing the messages.
                }
                channelGroups.addAll(channels.values());
                presenter.getChannels(channelGroups);
            }
        });
    }

        private void testMessageMethod(ChannelDescriptor cd) {

        cd.getChannel(new CallbackListener<Channel>() {
            @Override
            public void onSuccess(Channel channel) {

                Log.d(TAG, "onSuccess: synchronizedStatus "+channel.getSynchronizationStatus());

                channel.getMembersCount(new CallbackListener<Long>() {
                    @Override
                    public void onSuccess(Long aLong) {
                        Log.d(TAG, "onSuccess: channel:"+cd.getFriendlyName()+" members "+aLong);
                    }
                });

                channel.getMessagesCount(new CallbackListener<Long>() {
                    @Override
                    public void onSuccess(Long aLong) {
                        Log.d(TAG, "onSuccess: channel:"+cd.getFriendlyName()+" messages "+aLong);
                    }
                });

                channel.getUnconsumedMessagesCount(new CallbackListener<Long>() {
                    @Override
                    public void onSuccess(Long aLong) {
                        Log.d(TAG, "onSuccess: channel:"+cd.getFriendlyName()+" unConsumedMessages "+aLong);
                    }
                });

                if(channel.getMessages() != null) {
                   //test hard coded message.. 
                    Messages messages = channel.getMessages();
                    Message.Options options = Message.options().withBody("Hola from Android...");
                    messages.sendMessage(options, new CallbackListener<Message>() {
                        @Override
                        public void onSuccess(Message message) {
                            Log.d(TAG, "onSuccess: Message Sent..........");
                        }
                    });
                } else
                    Log.d(TAG, "onSuccess: Messages null :(:(:(:(");
            }
        });
    }

All relevant version information for issue.

#### Chat Android SDK

[3.0.0]

#### Android API

[Min Api 19]

**Comment by berkus** [comment]
As I see you don't wait for Channel.SynchronizationStatus.[isAtLeast](https://media.twiliocdn.com/sdk/android/chat/releases/3.0.1/docs/enumcom_1_1twilio_1_1chat_1_1Channel_1_1SynchronizationStatus.html#a22dc8977d010aaf6259f6390107b0775)(.ALL). You should.

**Comment by aalap03** [comment]
Thanks for the guide, I the boolean now. Also I will now use this link for updated docs 3.0.1 version, I used to look at 2.0.8.

**Comment by sharique112** [comment]
@berkus Can you please share code snippet for this?

**Comment by rusmonster** [comment]
@sharique112 
```
suspend fun Channel.waitForSynchronization(
        synchronizationStatus: Channel.SynchronizationStatus = Channel.SynchronizationStatus.ALL) {

    val complete = CompletableDeferred<Unit>()

    val listener = addListener(
            onSynchronizationChanged = { channel ->
                synchronized<Unit>(complete) {
                    if (complete.isCompleted) return@addListener

                    if (channel.synchronizationStatus == Channel.SynchronizationStatus.FAILED) {
                        val errorInfo = ErrorInfo(
                                CHANNEL_NOT_SYNCHRONIZED, "Channel synchronization failed: ${channel.sid}}")

                        complete.completeExceptionally(ChatException(errorInfo))
                    } else if (channel.synchronizationStatus.value >= synchronizationStatus.value) {
                        complete.complete(Unit)
                    }
                }
            }
    )

    complete.await()
    removeListener(listener)
}
```
