### ISSUE TITLE
ChannelListener is not working.

### ISSUE THREAD

**Issue by aalap03** [twilio/twilio-chat-demo-android#53]
### Description

I am on the `MessagesList` screen, displaying `Messages` for the `CurrentChannel`. I have added `ChannelListener` to get updates on messages added, deleted etc. I observe the log after adding the listener but only `onSynchronizationChanged` gets called once with Status `ALL`.

Please let me know if I am missing something here. 

     private void setupMessageValues() {

        if (getIntent() != null) {

            try {
                currentChannel = getIntent().getParcelableExtra(CHANNEL); //getting channel on click on the channel list
                currentChannel.typing();
                currentChannel.addListener(this); //adding listener

                if (currentChannel.getMessages() != null) {
                    channelMessages = currentChannel.getMessages();
                    channelMessages.setAllMessagesConsumedWithResult(allMessagesReadListener);
                    Log.d(TAG, "setupMessageValues: "+getIntent().getLongExtra(MESSAGES_COUNT, 0));
                    channelMessages.getLastMessages(100, new CallbackListener<List<Message>>() {
                        @Override
                        public void onSuccess(List<Message> messages) {
                            Log.d(TAG, "messages: " + messages.size());
                            convertTwilioMessagesToUI(messages, currentChannel.getMembers());
                        }
                    });
                } else
                    Toasty.error(this, "Messages null").show();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    @Override
    public void onMessageAdded(Message message) {
        Log.d(TAG, "onMessageAdded: ");
        addMyMessage(message); //works fine.
    }

    @Override
    public void onMessageUpdated(Message message, Message.UpdateReason updateReason) {
        Log.d(TAG, "onMessageUpdated: ");
    }

    @Override
    public void onMessageDeleted(Message message) {
        Log.d(TAG, "onMessageDeleted: ");
    }

    @Override
    public void onMemberAdded(Member member) {
        Log.d(TAG, "onMemberAdded: ");
    }

    @Override
    public void onMemberUpdated(Member member, Member.UpdateReason updateReason) {
        Log.d(TAG, "onMemberUpdated: ");
    }

    @Override
    public void onMemberDeleted(Member member) {
        Log.d(TAG, "onMemberDeleted: ");
    }

    @Override
    public void onTypingStarted(Channel channel, Member member) {
        Log.d(TAG, "onTypingStarted: ");

        member.getAndSubscribeUser(new CallbackListener<User>() {
            @Override
            public void onSuccess(User user) {
                Log.d(TAG, "onSuccess: ");
                typingIndicator.setVisibility(View.VISIBLE);
                typingIndicator.setText(user.getFriendlyName() + " is Typing...");
            }
        });
    }

    @Override
    public void onTypingEnded(Channel channel, Member member) {
        Log.d(TAG, "onTypingEnded: ");

        typingIndicator.setVisibility(View.GONE);
    }

    @Override
    public void onSynchronizationChanged(Channel channel) {
        Log.d(TAG, "onSynchronizationChanged: " + channel.getSynchronizationStatus());
    }

```java
// Code that help reproduce the issue
```

#### Expected Behavior
I expect the listener methods to be called on each events but I don't get any result for that.

#### Actual Behavior
Thus I can not update messages, I have to re-enter the screen to get updated messages.

#### Reproduces how Often
100%

#### Logs

Please collect logs as described [here](https://github.com/twilio/twilio-chat-demo-android/blob/master/REPORT_BUGS.md). Full unedited logs help reproduce and fix issues faster.

```
 D/ChatMessageList:: onSynchronizationChanged: ALL```

#### Chat Android SDK

[eg. 3.0.1]

#### Android API

[24]

#### Android Device

[Samsung Galaxy S7 Edge, samsung Galaxy Neo 5]

**Comment by berkus** [comment]
Please collect logs as described [here](https://github.com/twilio/twilio-chat-demo-android/blob/master/REPORT_BUGS.md). Full unedited logs help reproduce and fix issues faster.

**Comment by berkus** [comment]
But to point out exactly what your bug is:
`currentChannel = getIntent().getParcelableExtra(CHANNEL);`

This line, see #26 - this is currently not supported in Chat SDK.

**Comment by JEuler** [comment]
@berkus Sorry to write in the closed issue. But how I can manage the following situation:
I have fragment with chat channels inside and I want to open activity with chat details (messages). Should I use multiple fragments with childFragmentManager?

**Comment by berkus** [comment]
You need to somehow pass the channel without sending it over in a parcel.

Simplest way is to send only Channel SID and use an actual ChatClient to get channel from by its SID, this should work and will not lose the listeners.

**Comment by JEuler** [comment]
Ah, okay, that simple :) Thank you!

**Comment by berkus** [comment]
You're welcome :)
