### ISSUE TITLE
AccessManager instant expiring in case of irrelevant system date

### ISSUE THREAD

**Issue by DummyCo** [twilio/twilio-chat-demo-android#54]
### Description

Hi there! Seems like AccessManager expiring business logic is going crazy in case of irrelevant system date set.

### Steps to Reproduce

1. Turn off automatic date&time for system
2. Set some system date in future
3. Try to use AccessManager

#### Actual Behavior

Instant looped token expiring & refresh

### Versions

Access manager: 0.1.0
Twilio programmable chat: 3.1.1
SDK: 27

#### Android Device

Nexus 5X

Thank you!

**Comment by berkus** [comment]
It's expected, as AccessManager uses device's time stamp to calculate the token expiry on the device but you receive the token from the service which has the correct time in the past, so from AM standpoint that token is already expired.

Nothing crazy about that.

You may employ various tricks to try and reconcile this time difference, but reality is that you just need to set the correct clock on the device. Enabling automatic time&date is a good option to do so.

**Comment by DummyCo** [comment]
Hi, @berkus.
Well, I see, but reality is a bad tone to rely on wall clock time in Java/Android in scope of events scheduling and time intervals, especially in that behavior case. Common approach is all about deltas & _elapsedRealTime_.
Thank you!

**Comment by berkus** [comment]
The AccessManager is a completely optional component. If it's critical for you right now, I recommend writing your own service that would check expiry using some internet clock.

In the future, there are plans to get rid of AccessManager completely and send token expiry events from the service side. No ETA for release though.

**Comment by DummyCo** [comment]
Roger that, thank you.
Closing for now.
