### ISSUE TITLE
Attempt to invoke virtual method 'void com.twilio.chat.Members.inviteByIdentity(java.lang.String, com.twilio.chat.StatusListener)' on a null object reference

### ISSUE THREAD

**Issue by shrishailcne** [twilio/twilio-chat-demo-android#57]
I'm implementing Twilio's Programmable Chat using the Android SDK.

When the Chat is setup I create a new Channel (using channelBuilder()), and then join it (calling join()). Then I set the channel listener and I call channel.getMembers().inviteByIdentity. 
Note: It is working fine in debug mode, if i run normally it will crash at this point. 

Please help me.
Thanks

**Comment by berkus** [comment]
Did you check that the channel is fully synchronized before calling getMembers()?

See [getSynchronizationStatus](https://media.twiliocdn.com/sdk/android/chat/releases/3.1.1/docs/classcom_1_1twilio_1_1chat_1_1Channel.html#ad9f97a156b8f5e4bf1cab9d4ba14bd28) and [SynchronizationStatus](https://media.twiliocdn.com/sdk/android/chat/releases/3.1.1/docs/enumcom_1_1twilio_1_1chat_1_1Channel_1_1SynchronizationStatus.html).

It must be `isAtLeast(.ALL)` for getMembers() to work.

**Comment by shrishailcne** [comment]
channelStatus : "ALL" i checked i am getting.

**Comment by InI4** [comment]
This might not be helpful. But just in case. I've been an awful lot of channel.getMembers() null check workarounds in my code, cause I found no way to prevent it. It seemed to center around cases where the app was put in background, continued running an then pulled back in foreground.

**Comment by berkus** [comment]
Closing, we will do some further improvements on these getMembers()/getChannels() functions (most probably by just removing them completely).
