### ISSUE TITLE
Chat Notification

### ISSUE THREAD

**Issue by Kitlabs** [twilio/twilio-chat-demo-android#60]
I'm trying to implement chat notification in my application. And I'm just fed up to follow the steps provide by Twilio.

Is there anyone who can help me to implement that in simple steps.

Actually, i tired everything whatever they said to follow, but nothing is gonna happen.

**Comment by berkus** [comment]
Well, if you want some constructive feedback, specify which steps you did follow and what was the results/errors during these steps.

If you just want to vent your frustration, this is fine too, but not really actionable.

**Comment by berkus** [comment]
Closing as no feedback received.
