### ISSUE TITLE
Thumbnail not generated after sharing YouTube url in a channel

### ISSUE THREAD

**Issue by mayuroks** [twilio/twilio-chat-demo-android#62]
### Description

When you share a YouTube video in Facebook messenger or WhatsApp it generates a thumbnail and shows the video title as well. When I tried sending video in Twilio, thumbnail wasn't generated.

### Steps to Reproduce

1. Copy YouTube video url
2. Open the twilio chat demo app
3. Send the video url
4. No thumbnail is generated

#### Expected Behavior

sending YouTube url in a channel should generate a thumbail 
#### Actual Behavior

sending YouTube url in a channel did NOT generate a thumbail

**Comment by berkus** [comment]
Thumbnails are generated by the client. Feel free to implement any of the existing thumbnail preview solutions or devise your own.
