### ISSUE TITLE
 Request to EMS service has failed, unable to set FPA token

### ISSUE THREAD

**Issue by mramaswamyj** [twilio/twilio-chat-demo-android#63]
ChatClient.create with a token returns with error "Request to EMS service has failed, unable to set FPA token" . *The same works with IOS. The code used to work 2 months ago. I enabled the log using ChatClient.setLogLevel(android.util.Log.DEBUG). By this is a prototype client we coded using twilio-chat-demo as base code. As per the logs, I see the code attempts to send requests >>
trying to sendRequest to https://ems.us1.twilio.com/v1/token.. and failed in the end. Not able to make out the cause. Requesting any insight on this problem.

Here are the logs >>
 13:05:37.589 D/jni_mate(18758): Got method ID 0x89a18a78 for method onError(Lcom/twilio/chat/ErrorInfo;)V
09-25 13:05:37.612 I/TWC: TNHttpTransportClient(18758):         2144241952 | 09/25/13:05:37.611 | INFO     | 6      | TNHttpTransportClient | trying to send request to: https://ems.us1.twilio.com/v1/token
09-25 13:05:37.612 I/TWC: TNRawHttp(18758):         2144241952 | 09/25/13:05:37.612 | INFO     | 7      | TNRawHttp | trying to sendRequest to https://ems.us1.twilio.com/v1/token
09-25 13:05:37.633 D/TWC: TNWebsocket(18758):         2139097376 | 09/25/13:05:37.633 | DEBUG    | 9      | TNWebsocket | Trying to establish connection to: https://tsock.us1.twilio.com
09-25 13:05:38.048 I/TWC: TNHttpTransportClient(18758):         2140141856 | 09/25/13:05:38.048 | INFO     | 6      | TNHttpTransportClient | trying to send request to: https://ems.us1.twilio.com/v1/token
09-25 13:05:38.048 I/TWC: TNRawHttp(18758):         2140141856 | 09/25/13:05:38.048 | INFO     | 7      | TNRawHttp | trying to sendRequest to https://ems.us1.twilio.com/v1/token
09-25 13:05:38.384 I/TWC: TNHttpTransportClient(18758):         2140141856 | 09/25/13:05:38.384 | INFO     | 6      | TNHttpTransportClient | trying to send request to: https://ems.us1.twilio.com/v1/token
09-25 13:05:38.384 I/TWC: TNRawHttp(18758):         2140141856 | 09/25/13:05:38.384 | INFO     | 7      | TNRawHttp | trying to sendRequest to https://ems.us1.twilio.com/v1/token
09-25 13:05:38.714 I/TWC: TNHttpTransportClient(18758):         2140141856 | 09/25/13:05:38.714 | INFO     | 6      | TNHttpTransportClient | trying to send request to: https://ems.us1.twilio.com/v1/token
09-25 13:05:38.714 I/TWC: TNRawHttp(18758):         2140141856 | 09/25/13:05:38.714 | INFO     | 7      | TNRawHttp | trying to sendRequest to https://ems.us1.twilio.com/v1/token
09-25 13:05:39.056 I/TWC: TNHttpTransportClient(18758):         2140141856 | 09/25/13:05:39.056 | INFO     | 6      | TNHttpTransportClient | trying to send request to: https://ems.us1.twilio.com/v1/token
09-25 13:05:39.056 I/TWC: TNRawHttp(18758):         2140141856 | 09/25/13:05:39.056 | INFO     | 7      | TNRawHttp | trying to sendRequest to https://ems.us1.twilio.com/v1/token
09-25 13:05:39.408 I/TWC: TNHttpTransportClient(18758):         2140141856 | 09/25/13:05:39.408 | INFO     | 6      | TNHttpTransportClient | trying to send request to: https://ems.us1.twilio.com/v1/token
09-25 13:05:39.409 I/TWC: TNRawHttp(18758):         2140141856 | 09/25/13:05:39.409 | INFO     | 7      | TNRawHttp | trying to sendRequest to https://ems.us1.twilio.com/v1/token
09-25 13:05:39.804 I/TWC: TNHttpTransportClient(18758):         2140141856 | 09/25/13:05:39.804 | INFO     | 6      | TNHttpTransportClient | trying to send request to: https://ems.us1.twilio.com/v1/token
09-25 13:05:39.804 I/TWC: TNRawHttp(18758):         2140141856 | 09/25/13:05:39.804 | INFO     | 7      | TNRawHttp | trying to sendRequest to https://ems.us1.twilio.com/v1/token
09-25 13:05:40.074 D/TWC: TNWebsocket(18758):         2139097376 | 09/25/13:05:40.073 | DEBUG    | 9      | TNWebsocket | Trying to establish connection to: https://tsock.us1.twilio.com
09-25 13:05:40.113 I/TWC: TNHttpTransportClient(18758):         2140141856 | 09/25/13:05:40.113 | INFO     | 6      | TNHttpTransportClient | trying to send request to: https://ems.us1.twilio.com/v1/token
09-25 13:05:40.113 I/TWC: TNRawHttp(18758):         2140141856 | 09/25/13:05:40.113 | INFO     | 7      | TNRawHttp | trying to sendRequest to https://ems.us1.twilio.com/v1/token
09-25 13:05:40.442 I/TWC: TNHttpTransportClient(18758):         2140141856 | 09/25/13:05:40.442 | INFO     | 6      | TNHttpTransportClient | trying to send request to: https://ems.us1.twilio.com/v1/token
09-25 13:05:40.442 I/TWC: TNRawHttp(18758):         2140141856 | 09/25/13:05:40.442 | INFO     | 7      | TNRawHttp | trying to sendRequest to https://ems.us1.twilio.com/v1/token
09-25 13:05:40.763 I/TWC: TNHttpTransportClient(18758):         2140141856 | 09/25/13:05:40.763 | INFO     | 6      | TNHttpTransportClient | trying to send request to: https://ems.us1.twilio.com/v1/token
09-25 13:05:40.763 I/TWC: TNRawHttp(18758):         2140141856 | 09/25/13:05:40.763 | INFO     | 7      | TNRawHttp | trying to sendRequest to https://ems.us1.twilio.com/v1/token
09-25 13:05:41.100 I/TWC: TNHttpTransportClient(18758):         2140141856 | 09/25/13:05:41.100 | INFO     | 6      | TNHttpTransportClient | trying to send request to: https://ems.us1.twilio.com/v1/token
09-25 13:05:41.100 I/TWC: TNRawHttp(18758):         2140141856 | 09/25/13:05:41.100 | INFO     | 7      | TNRawHttp | trying to sendRequest to https://ems.us1.twilio.com/v1/token
09-25 13:05:41.441 I/TWC: TNHttpTransportClient(18758):         2140141856 | 09/25/13:05:41.440 | INFO     | 6      | TNHttpTransportClient | trying to send request to: https://ems.us1.twilio.com/v1/token
09-25 13:05:41.441 I/TWC: TNRawHttp(18758):         2140141856 | 09/25/13:05:41.441 | INFO     | 7      | TNRawHttp | trying to sendRequest to https://ems.us1.twilio.com/v1/token
09-25 13:05:41.755 I/TWC: TNHttpTransportClient(18758):         2140141856 | 09/25/13:05:41.755 | INFO     | 6      | TNHttpTransportClient | trying to send request to: https://ems.us1.twilio.com/v1/token
09-25 13:05:41.755 I/TWC: TNRawHttp(18758):         2140141856 | 09/25/13:05:41.755 | INFO     | 7      | TNRawHttp | trying to sendRequest to https://ems.us1.twilio.com/v1/token
09-25 13:05:42.069 I/TWC: TNHttpTransportClient(18758):         2140141856 | 09/25/13:05:42.069 | INFO     | 6      | TNHttpTransportClient | trying to send request to: https://ems.us1.twilio.com/v1/token
09-25 13:05:42.069 I/TWC: TNRawHttp(18758):         2140141856 | 09/25/13:05:42.069 | INFO     | 7      | TNRawHttp | trying to sendRequest to https://ems.us1.twilio.com/v1/token
09-25 13:05:44.423 D/TWC: TNWebsocket(18758):         2139097376 | 09/25/13:05:44.423 | DEBUG    | 9      | TNWebsocket | Trying to establish connection to: https://tsock.us1.twilio.com
09-25 13:05:47.405 I/TWC: TNHttpTransportClient(18758):         2140141856 | 09/25/13:05:47.405 | INFO     | 6      | TNHttpTransportClient | trying to send request to: https://ems.us1.twilio.com/v1/token
09-25 13:05:47.405 I/TWC: TNRawHttp(18758):         2140141856 | 09/25/13:05:47.405 | INFO     | 7      | TNRawHttp | trying to sendRequest to https://ems.us1.twilio.com/v1/token
09-25 13:05:47.703 I/TWC: TNHttpTransportClient(18758):        -2142369504 | 09/25/13:05:47.703 | INFO     | 6      | TNHttpTransportClient | trying to send request to: https://ems.us1.twilio.com/v1/token
09-25 13:05:47.703 I/TWC: TNRawHttp(18758):        -2142369504 | 09/25/13:05:47.703 | INFO     | 7      | TNRawHttp | trying to sendRequest to https://ems.us1.twilio.com/v1/token
09-25 13:05:48.008 I/TWC: TNHttpTransportClient(18758):        -2144458464 | 09/25/13:05:48.008 | INFO     | 6      | TNHttpTransportClient | trying to send request to: https://ems.us1.twilio.com/v1/token
09-25 13:05:48.008 I/TWC: TNRawHttp(18758):        -2144458464 | 09/25/13:05:48.008 | INFO     | 7      | TNRawHttp | trying to sendRequest to https://ems.us1.twilio.com/v1/token
09-25 13:05:48.318 I/TWC: TNHttpTransportClient(18758):        -2145502944 | 09/25/13:05:48.318 | INFO     | 6      | TNHttpTransportClient | trying to send request to: https://ems.us1.twilio.com/v1/token
09-25 13:05:48.318 I/TWC: TNRawHttp(18758):        -2145502944 | 09/25/13:05:48.318 | INFO     | 7      | TNRawHttp | trying to sendRequest to https://ems.us1.twilio.com/v1/token
09-25 13:05:48.585 I/TWC: TNHttpTransportClient(18758):        -2143413984 | 09/25/13:05:48.585 | INFO     | 6      | TNHttpTransportClient | trying to send request to: https://ems.us1.twilio.com/v1/token
09-25 13:05:48.585 I/TWC: TNRawHttp(18758):        -2143413984 | 09/25/13:05:48.585 | INFO     | 7      | TNRawHttp | trying to sendRequest to https://ems.us1.twilio.com/v1/token
09-25 13:05:48.912 I/TWC: TNHttpTransportClient(18758):         2140141856 | 09/25/13:05:48.911 | INFO     | 6      | TNHttpTransportClient | trying to send request to: https://ems.us1.twilio.com/v1/token
09-25 13:05:48.912 I/TWC: TNRawHttp(18758):         2140141856 | 09/25/13:05:48.912 | INFO     | 7      | TNRawHttp | trying to sendRequest to https://ems.us1.twilio.com/v1/token
09-25 13:05:49.211 I/TWC: TNHttpTransportClient(18758):         2140141856 | 09/25/13:05:49.211 | INFO     | 6      | TNHttpTransportClient | trying to send request to: https://ems.us1.twilio.com/v1/token
09-25 13:05:49.211 I/TWC: TNRawHttp(18758):         2140141856 | 09/25/13:05:49.211 | INFO     | 7      | TNRawHttp | trying to sendRequest to https://ems.us1.twilio.com/v1/token
09-25 13:05:49.475 I/TWC: TNHttpTransportClient(18758):         2140141856 | 09/25/13:05:49.475 | INFO     | 6      | TNHttpTransportClient | trying to send request to: https://ems.us1.twilio.com/v1/token
09-25 13:05:49.475 I/TWC: TNRawHttp(18758):         2140141856 | 09/25/13:05:49.475 | INFO     | 7      | TNRawHttp | trying to sendRequest to https://ems.us1.twilio.com/v1/token
09-25 13:05:49.812 I/TWC: TNHttpTransportClient(18758):         2140141856 | 09/25/13:05:49.812 | INFO     | 6      | TNHttpTransportClient | trying to send request to: https://ems.us1.twilio.com/v1/token
09-25 13:05:49.812 I/TWC: TNRawHttp(18758):         2140141856 | 09/25/13:05:49.812 | INFO     | 7      | TNRawHttp | trying to sendRequest to https://ems.us1.twilio.com/v1/token
09-25 13:05:50.120 I/TWC: TNHttpTransportClient(18758):        -2140280544 | 09/25/13:05:50.120 | INFO     | 6      | TNHttpTransportClient | trying to send request to: https://ems.us1.twilio.com/v1/token
09-25 13:05:50.120 I/TWC: TNRawHttp(18758):        -2140280544 | 09/25/13:05:50.120 | INFO     | 7      | TNRawHttp | trying to sendRequest to https://ems.us1.twilio.com/v1/token
09-25 13:05:50.402 I/TWC: TNHttpTransportClient(18758):        -2136102624 | 09/25/13:05:50.401 | INFO     | 6      | TNHttpTransportClient | trying to send request to: https://ems.us1.twilio.com/v1/token
09-25 13:05:50.402 I/TWC: TNRawHttp(18758):        -2136102624 | 09/25/13:05:50.402 | INFO     | 7      | TNRawHttp | trying to sendRequest to https://ems.us1.twilio.com/v1/token
09-25 13:05:50.782 I/TWC: TNHttpTransportClient(18758):        -2135058144 | 09/25/13:05:50.782 | INFO     | 6      | TNHttpTransportClient | trying to send request to: https://ems.us1.twilio.com/v1/token
09-25 13:05:50.782 I/TWC: TNRawHttp(18758):        -2135058144 | 09/25/13:05:50.782 | INFO     | 7      | TNRawHttp | trying to sendRequest to https://ems.us1.twilio.com/v1/token
09-25 13:05:51.094 I/TWC: TNHttpTransportClient(18758):         2144241952 | 09/25/13:05:51.094 | INFO     | 6      | TNHttpTransportClient | trying to send request to: https://ems.us1.twilio.com/v1/token
09-25 13:05:51.095 I/TWC: TNRawHttp(18758):         2144241952 | 09/25/13:05:51.095 | INFO     | 7      | TNRawHttp | trying to sendRequest to https://ems.us1.twilio.com/v1/token
09-25 13:05:51.361 I/TWC: TNHttpTransportClient(18758):         2140141856 | 09/25/13:05:51.361 | INFO     | 6      | TNHttpTransportClient | trying to send request to: https://ems.us1.twilio.com/v1/token
09-25 13:05:51.361 I/TWC: TNRawHttp(18758):         2140141856 | 09/25/13:05:51.361 | INFO     | 7      | TNRawHttp | trying to sendRequest to https://ems.us1.twilio.com/v1/token
09-25 13:05:51.808 I/TWC: TNHttpTransportClient(18758):         2147375392 | 09/25/13:05:51.808 | INFO     | 6      | TNHttpTransportClient | trying to send request to: https://ems.us1.twilio.com/v1/token
09-25 13:05:51.808 I/TWC: TNRawHttp(18758):         2147375392 | 09/25/13:05:51.808 | INFO     | 7      | TNRawHttp | trying to sendRequest to https://ems.us1.twilio.com/v1/token
09-25 13:05:52.141 I/TWC: TNHttpTransportClient(18758):         2145286432 | 09/25/13:05:52.141 | INFO     | 6      | TNHttpTransportClient | trying to send request to: https://ems.us1.twilio.com/v1/token
09-25 13:05:52.141 I/TWC: TNRawHttp(18758):         2145286432 | 09/25/13:05:52.141 | INFO     | 7      | TNRawHttp | trying to sendRequest to https://ems.us1.twilio.com/v1/token
09-25 13:05:52.422 I/TWC: TNHttpTransportClient(18758):         2140141856 | 09/25/13:05:52.422 | INFO     | 6      | TNHttpTransportClient | trying to send request to: https://ems.us1.twilio.com/v1/token
09-25 13:05:52.422 I/TWC: TNRawHttp(18758):         2140141856 | 09/25/13:05:52.422 | INFO     | 7      | TNRawHttp | trying to sendRequest to https://ems.us1.twilio.com/v1/token
09-25 13:05:52.766 E/MSG_CLIENT_MessageClient(18758): TWILIOM Error creating Twilio Chat Client: Request to EMS service has failed, unable to set FPA token

Thanks
Murali

**Comment by berkus** [comment]
Looks like you don't have internet access?

**Comment by berkus** [comment]
Hi, please try `4.0.0-rc11` and send your feedback.

**Comment by berkus** [comment]
Closing as there is no response.
