### ISSUE TITLE
App Is Crashing On Android 7.1 and Above While Initializing ChatClient 

### ISSUE THREAD

**Issue by VIKAS9899** [twilio/twilio-chat-demo-android#64]
--------- beginning of crash
10-03 18:50:53.753 19041-19041/com.app.tillo A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 19041 (com.app.tillo)
10-03 18:50:53.839 20432-20432/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
    Build fingerprint: 'motorola/lux_retasia_ds/lux_uds:7.1.1/NPD26.48-24-1/1:user/release-keys'
    Revision: 'p2c0'
    ABI: 'arm'
10-03 18:50:53.840 20432-20432/? A/DEBUG: pid: 19041, tid: 19041, name: com.app.tillo  >>> com.app.tillo <<<
    signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
10-03 18:50:53.846 20432-20432/? A/DEBUG: Abort message: 'Error, cannot access an invalid/free'd bitmap here!'
        r0 00000000  r1 00004a61  r2 00000006  r3 00000008
        r4 a81cd58c  r5 00000006  r6 a81cd534  r7 0000010c
        r8 00000000  r9 a5484400  sl 00000000  fp 00000000
        ip 0000000b  sp beea9578  lr a5b2d407  pc a5b2fc64  cpsr 200f0010
10-03 18:50:53.853 20432-20432/? A/DEBUG: backtrace:
        #00 pc 00049c64  /system/lib/libc.so (tgkill+12)
        #01 pc 00047403  /system/lib/libc.so (pthread_kill+34)
        #02 pc 0001d555  /system/lib/libc.so (raise+10)
        #03 pc 000190a1  /system/lib/libc.so (__libc_android_abort+34)
        #04 pc 00017104  /system/lib/libc.so (abort+4)
        #05 pc 0000c3d9  /system/lib/libcutils.so (__android_log_assert+112)
        #06 pc 0009f073  /system/lib/libandroid_runtime.so (_ZNK7android6Bitmap11assertValidEv+18)
        #07 pc 0009f0ef  /system/lib/libandroid_runtime.so (_ZN7android6Bitmap11getSkBitmapEP8SkBitmap+6)
        #08 pc 000a7e2f  /system/lib/libandroid_runtime.so
        #09 pc 7365dd17  /data/dalvik-cache/arm/system@framework@boot.oat (offset 0x28e1000)
10-03 18:50:55.039 2366-20433/? W/ActivityManager: Process com.app.tillo has crashed too many times: killing!
      Force finishing activity com.app.tillo/.features.HomeScreen.HomeActivity
10-03 18:50:55.044 2366-2472/? I/BootReceiver: Copying /data/tombstones/tombstone_07 to DropBox (SYSTEM_TOMBSTONE)
10-03 18:50:55.057 11971-11996/? I/CarrierServices: [1426] bsd.a: FiST: Wifi connectivity status true
10-03 18:50:55.060 11971-11996/? I/CarrierServices: [1426] bsi.d: Connected state: [1], networkType: [true]
10-03 18:50:55.061 11971-12033/? I/CarrierServices: [1444] ctx.a: CarrierServices.apk is not sim call manager. Not enabling MMTel.
    [1444] baa.run: (MMTel): : Ignoring Network Change based on IMS preferences

**Comment by berkus** [comment]
Please collect logs as described [here](https://github.com/twilio/twilio-chat-demo-android/blob/master/REPORT_BUGS.md). Full unedited logs help reproduce and fix issues faster.
