### ISSUE TITLE
Completely broken with many classes missing

### ISSUE THREAD

**Issue by amiga** [twilio/twilio-chat-demo-android#65]
almost all classes are missing example:

import com.twilio.chat.Channel;
import com.twilio.chat.StatusListener;
import com.twilio.chat.CallbackListener;
import com.twilio.chat.ChatClientListener;
import com.twilio.chat.ChatClient;
import com.twilio.chat.ErrorInfo;
import com.twilio.chat.User;
import com.twilio.chat.internal.HandlerUtil;

when trying to sync error comes up 

No matching client found for package name 'com.twilio.chat.demo.debug'

**Comment by berkus** [comment]
Which SDK version?

Did you change anything in the manifest? Did you generate google-settings.json file for your app? Did you call the app `com.twilio.chat.demo.debug` in firebase console?

**Comment by amiga** [comment]
Just tried example code straight from github, i put in google-settings.json, not entered it into firebase yet because it wont compile. How to get the code to compile ?

**Comment by berkus** [comment]
Follow the steps [outlined in the readme file](https://github.com/twilio/twilio-chat-demo-android#building).

**Comment by amiga** [comment]
ok, this now gives error:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':chat-demo-android:processDebugGoogleServices'.
> No matching client found for package name 'com.twilio.chat.demo.debug'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1s
21 actionable tasks: 17 executed, 4 up-to-date

**Comment by amiga** [comment]
In Android Studio compile errors now gone but i always get "No matching client found for package name 'com.twilio.chat.demo.debug'" when i try to run it.

**Comment by amiga** [comment]
Actually R wont generate or import on most files either.

**Comment by amiga** [comment]
Wasted 5 hours on this, complete rubbish.

**Comment by berkus** [comment]
Closing as there's no response.
