### ISSUE TITLE
Library min sdk support

### ISSUE THREAD

**Issue by kristiyanP** [twilio/twilio-chat-demo-android#66]
### Description
In our use-case **(B2B)** we need to support **api16+.**

The current programmable-chat **v3.1.1** supports **api19+ taking away 3,8%** of our user base.

We have checked the release candidate **v4.0.0-rc12** which seems to **support from api21+** which will take away a total of **11,6%** of our user base!!

### Important
Please keep into account that a **10%** of android market share is a huge percentage! And because our target is **B2B**  which requires huge support that makes a **BIG** difference for us.

### Question
Is there a reason for this **insane support**?
Can we do something to support older api?

P.s.
We have checked and on the emulator api17 looks stable while on emulator api16 keeps crashing natively because of a ssl error.

**Comment by berkus** [comment]
API 19 has always been the minimum, on arm64 devices API 21 is probably the reasonable minimum because there are no older arm64 devices anyway.

Contact us through the support portal and we can discuss the possibility of a special API 16 build.

**Comment by kristiyanP** [comment]
I don't think the architecture has anything to do with it... as the test has been executed on the same architecture but different sdk versions.

Thank you
I will submit a ticket with the request for a lower minSdk build.

**Comment by sschendel** [comment]
Can you help clarify the reason SDK requires a minSdk of 21?

**Comment by berkus** [comment]
C++17 support. It could and have been running with API 19 as well, although somewhat unofficially.
