### ISSUE TITLE
Request to EMS service has failed, unable to set FPA token

### ISSUE THREAD

**Issue by nidhinprathap** [twilio/twilio-chat-demo-android#70]
### Description
It was working earlier but suddenly it stopped working. Even the sample app returns the same. But the iOS version works. Is there any configuration that I need to change & why is it only reflecting android.

Access Token 

> REMOVED

### Steps to Reproduce

While Initiating a chat client

#### Actual Behavior

When I try to create a Chat Client I get 

> Request to EMS service has failed, unable to set FPA token

#### Reproduces how Often

Currently always

#### Logs

LOGS ill Attach a file

### Versions

All relevant version information for issue.

#### Chat Android SDK

0.12.2

#### Android API

9

#### Android Device

All

**Comment by nidhinprathap** [comment]
Updated
and attached the log

**Comment by berkus** [comment]
The log does not contain even a single log line from the Twilio SDK. Please follow the [manual] to properly record a log file.

**Comment by nidhinprathap** [comment]
Thats the log im getting

> ChatClient(native):       543149008200 | 10/16/15:31:05.841 | DEBUG    | ChatClient(native) | Started ChatClient nativeCreate()
10-16 15:31:05.843  2324  2324 D ChatUtils(native):       543149008200 | 10/16/15:31:05.843 | DEBUG    | ChatUtils(native) | Didn't find default onSuccess()
10-16 15:31:05.844  2324  2324 D ChatUtils(native):       543149008200 | 10/16/15:31:05.844 | DEBUG    | ChatUtils(native) | Looking for backup onSuccess()
10-16 15:31:05.844  2324  2324 W ChatUtils(native):       543149008200 | 10/16/15:31:05.844 | WARNING  | ChatUtils(native) | ListenerWrapper default onSuccess() not found
10-16 15:31:05.852  2324  2832 D         :       540448929008 | 10/16/15:31:05.852 | DEBUG    |  | Using root certificate store: /data/user/0/com.sendaride.carepartner/files/rootcert.pem
10-16 15:31:05.856  2324  2832 D ChatClient(native):       540448929008 | 10/16/15:31:05.856 | DEBUG    | ChatClient(native) | Creating notification client observer

**Comment by nidhinprathap** [comment]
[log1.txt](https://github.com/twilio/twilio-chat-demo-android/files/2482480/log1.txt)

**Comment by berkus** [comment]
It still does not contain any Twilio SDK log lines. You could check yourself before sending - just grep for EMS or TWC.

**Comment by nidhinprathap** [comment]
is it because of the sdk version.. the previous version would have lesser logs?

**Comment by berkus** [comment]
`0.12.2` has been out of support a while, try using a recent version. 0.x will be hard end-of-lifed soon.

**Comment by nidhinprathap** [comment]
Ok, I'll just set up the project. But why did it stop all of a sudden without any notice & why is Web and ios working.

**Comment by berkus** [comment]
Because they are more recent version, I would assume.

**Comment by nidhinprathap** [comment]
Ok updated to the latest, it started working. Just a suggestion as Twilio is being widely used by enterprises now, it will be great to have a section in Admin Dashboard telling that the library is about to get **obsolete**  or some mail notification to admin.

**Comment by nidhinprathap** [comment]
Reopening the issue :- 

Im On the latest sdk :- 3.1.1

I can see the error still coming sometimes. its like 90% it works and rest its coming as error.

**Comment by berkus** [comment]
Hi, can you check with 4.0.0-rc18 and post here if anything changes?

**Comment by berkus** [comment]
Closing, no response.
