### ISSUE TITLE
Old Java Repo

### ISSUE THREAD

**Issue by imran-samed** [twilio/twilio-chat-demo-android#73]
There is no updation in repo from last more than 1 year and so much changes in twilio sdk, why you guys are not updating it.

**Comment by berkus** [comment]
Use kotlin version to see all the latest changes.

**Comment by imran-samed** [comment]
I'm working with java.

**Comment by imran-samed** [comment]
@berkus 

I'm working with java.

**Comment by imran-samed** [comment]
@berkus 
I'm developing application using Java.

**Comment by berkus** [comment]
Thats fine, read the docs then. Demo app is just a sample, sdk api is in java.

**Comment by berkus** [comment]
No response, closing.
