### ISSUE TITLE
Request to EMS service has failed, unable to set FPA token

### ISSUE THREAD

**Issue by amiga** [twilio/twilio-chat-demo-android#74]
### Description

Trying to log into chat im getting this error

Request to EMS service has failed, unable to set FPA token

I see a lot of these too

Poco exception while sending request over http: SSL Exception: error:1000007e:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED

Samsung S7

**Comment by berkus** [comment]
You did not specify sdk version. Theres a number of fields you must fill when opening an issue, they are marked in bold. 

Try 4.0.0-rc13 meanwhile.

**Comment by berkus** [comment]
4.0 is as usual [on bintray](https://bintray.com/twilio/releases/chat-android/). No idea what is Kotlin-only - the SDK has always supported and will always support Java.

**Comment by amiga** [comment]
where do I actually specify this ?when i said 2.1.1 i meant "com.twilio:video-android"
and this is taken directly from your own example project.

**Comment by berkus** [comment]
Just replace 2.1.1 with 4.0.0-rc13 and you’re good.

**Comment by berkus** [comment]
Hi, can you check with 4.0.0-rc18 and post here if anything changes?

**Comment by berkus** [comment]
Closing, no response.
