### ISSUE TITLE
Android chat SDK initializing Critical issue - ChatClient build unsuccessful

### ISSUE THREAD

**Issue by TonyRise** [twilio/twilio-chat-demo-android#76]
Hi Twilio support team!
We have a big project with iOS, Android and WEB platforms and a backend using Python. At some point of development we started to choose from a wide range of chat and video services and chosen Twilio as an advanced and reliable one, that supports the platforms we use.

WEB and iOS works great. But we are facing a problem with Android chats - when we are **trying to create ChatClient** - it is not created, Twilio SDK responses with **error that access token is not valid**.
Android code that we use for it:
`public void build(String token, final TaskCompletionListener<ChatClient, String> listener) {
   ChatClient.Properties props =
       new ChatClient.Properties.Builder()
           .setRegion("us1")
           .createProperties();
   this.buildListener = listener;
   ChatClient.create(context.getApplicationContext(),
       token,
       props,
       this);}`

Interesting thing is that video call is working good, while mechanism of access token creation is the same as for chats. Here is our code example, that we took from Twilio example, how we create token on server (Python code):
`def get_chat_token(identity):
       from twilio.jwt.access_token import AccessToken
       from twilio.jwt.access_token.grants import ChatGrant
       # required for all twilio access tokens
       account_sid = settings.TWILIO_API['accountSID']
       api_key = settings.TWILIO_API['backend']['sid']
       api_secret = settings.TWILIO_API['backend']['secret']
       # required for Chat grants
       service_sid = settings.TWILIO_API['serviceSID']
       # Create access token with credentials
       token = AccessToken(account_sid, api_key, api_secret, identity=identity, ttl=3600)
       # Create an Chat grant and add to token
       chat_grant = ChatGrant(service_sid=service_sid)
       token.add_grant(chat_grant)
       # Return token info as JSON
       return token.to_jwt()`

I tried the same (to create a ChatClient) using Twilio sample application, I inserted our token into it - it doesn't work either, with the same error. Link to this sample - https://github.com/twilio/twilio-chat-demo-android

Here is example of the token that we use:
`eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImN0eSI6InR3aWxpby1mcGE7dj0xIn0.eyJqdGkiOiJTSzZjMzVlNGNkY2FmOTY5YTZjZTJlYTczNjM4ZWViMzRkLTE1NDEwODM0OTAiLCJncmFudHMiOnsiY2hhdCI6eyJzZXJ2aWNlX3NpZCI6IklTZTZhN2JmYWJkNWU1NDRiZGI4Zjc1OGNlNmE0YWQzYzMifSwiaWRlbnRpdHkiOiJwYXRpZW50MTYxIn0sImlzcyI6IlNLNmMzNWU0Y2RjYWY5NjlhNmNlMmVhNzM2MzhlZWIzNGQiLCJleHAiOjE1NDEwODcwOTAsInN1YiI6IkFDODc5MjU3MTZmOGNhMzBhY2M1MzRiNGRiYTM0MjM5YWYifQ.jFSdnBbREshOzPv6Cde1WK07y82CKLmaamnnOg-4ttI`

Error text that we received was "provided grant token is not authentic or has expired"
I updated Twilio SDK today (8-Nov-2018), now error text is changed to "**Request to EMS service has failed, unable to set FPA token**"
Twilio support recommended us the only thing is to remove NBF field, I tried it and it didn't help. All further communication didn't have any direct recomendation that could help.
Our Android SDK - 26; Chat Android SDK - 3.1.0 (before we used 0.11.2); Actual for all Android devices, e.g. we used Nexus 7 and Google Pixel 2

My first request about this problem was on 15-Oct-2018. Since that moment three weeks passed and there is no progress in handling of the issue. I consider it's critical for such service as Twilio. The **success of our project faces a critical risk, if the issue is not fixed**. Otherwise we are failing the project by choosing Twilio, instead of other services.
I summon Twilio support to **help with the issue fixing**. Not by some languid recommendations but by direct actions. Please help, **looking forward for your efficient response.**

Thanks in advance,
Tony

**Comment by berkus** [comment]
1. Have you tried the **latest** versions of the Twilio SDK: 3.1.1 released or 4.0.0-rc13 for pre-release?

**Comment by berkus** [comment]
2. Please provide logs. The template for opening an issue clearly states that logs need to be provided. I do not see any logs provided however.

**Comment by berkus** [comment]
3. The token itself looks valid, so lets see what the service responds in the logs.

**Comment by TonyRise** [comment]
Hi @berkus , thanks for the response!
I have updated SDK version to 3.1.1 but this didn't help a lot. Here are the links to our logs:
3.1.1 https://drive.google.com/open?id=1QCAasI57w-Y2PJ8FBCLdBBHMoM4Mg5no
and 4.0.0-rc13 https://drive.google.com/open?id=1xyiGcdyJfuTaFAKrTwMFYKe5TcRRpAGM

**Comment by berkus** [comment]
Thanks, looking!

**Comment by berkus** [comment]
It looks like the token is actually expired.

In the log for 4.0.0-rc13 I can see that local AccessManager fires onTokenExpired events even before you reach out to network:
```
11-13 14:10:17.284 10300 10300 V ChatClientManager: onTokenExpired() called with: accessManager = [com.twilio.accessmanager.AccessManager@155d4a3]
11-13 14:10:17.285 10300 10300 D ChatClientManager: onTokenExpired() called with: accessManager = [com.twilio.accessmanager.AccessManager@155d4a3]
.....
and then connection to websocket starts and ends with error message:
.....
11-13 14:10:18.761 10300 11023 D TWC     : {"method":"reply","id":"RQdaff089bdb3d4a94a1410111730af3f1","payload_size":0,"status":{"description":"Access Token expired or expiration date invalid","errorCode":20104,"code":401,"status":"AUTHENTICATION_FAILED"}}
```

To double check, in what timezone are these phones/logs captured?

**Comment by TonyRise** [comment]
Thanks, your response made us check if there could be cause in timezone. 
So we decided to change our token TTL to 24 hours to cover all timezones and it helped.
The thing is that we are located in GMT+2 timezone.
I guess the reason could be in our code here:
`ChatClient.Properties props = new ChatClient.Properties.Builder().setRegion("us1").createProperties();`
So, can you suggest us to use some other values instead of `us1` to use and keep the app localized?
Or do we actually need to use `setRegion` method?

**Comment by berkus** [comment]
setRegion only selects which servers to connect to, and if you did not purchase/enable instances specifically, us1 is the only available option then.

Make sure your token generator is correct - jwt expiry time is specified with UTC unix timestamp as per the [jwt RFC](https://tools.ietf.org/html/rfc7519#section-4.1.4). You're probably specifying it in your local time zone which is incorrect.

**Comment by TonyRise** [comment]
I'd be happy if it could be the reason. But here is how it goes: we are generating the token on our server (the code I wrote above). Mobile app doesn't have any special influence to it. 
And the most interesting detail is that the same token is valid on the iOS app with their Twilio SDK and is rejected by Twilio Android SDK. 
How this could be?

**Comment by berkus** [comment]
This looks pretty impossible indeed.

**Comment by berkus** [comment]
But you say switching to maximum token lifetime helped, so this may be the timing issue - depends on when you test on ios and when you test on android - is it happening at the same time? Have you copied your token to jwt.io and checked that exp field shows correct values and is not at that moment expired?

**Comment by berkus** [comment]
Can you try again with the older token that caused you trouble, but use AccessManager methods to check what it thinks was the token expiration time?

You could use these two methods:
```
/**
 * Returns whether the current access token has expired.
 */
public boolean isTokenExpired();

/**
 * Returns the expiration date for the current access token.
 */
public Date getTokenExpirationDate();
```

**Comment by berkus** [comment]
You will need to generate it again, of course, just use the previous TTL settings.

**Comment by TonyRise** [comment]
It is totally strange but today we tried to bring TTL back to one hour and... it works now! Still I'm confused what was the cause of the problem but now it seems to be resolved.

**Comment by berkus** [comment]
I'm pretty sure that clock skew could be the problem. Either that or invalid TZ when generating tokens - double check the clocks on the machine that issues tokens.

**Comment by berkus** [comment]
Issue resolved, so closing.
