### ISSUE TITLE
 Poco exception while sending request

### ISSUE THREAD

**Issue by AjithNoah** [twilio/twilio-chat-demo-android#77]
Hello.. i am using twilio to send media messages.. when i try to send image or video i got this error...

11-23 10:55:06.856 23948-23948/com.taggery I/TWC: TNRawHttp:        -1323506380 | 11/23/10:55:06.856 | INFO     | 29     | TNRawHttp | trying to sendRequest to https://mcs.us1.twilio.com/v1/Services/IS29a0bc76d13c433188a40bf60a4b5600/Media/MEfce338b4ee081845bcf587ded57e4980
11-23 10:55:06.906 23948-23948/com.taggery I/chatadpater: This is a media message with SID ME13baad1cb72306020f5d72388545a8e2, type image/jpeg, name ProfileImg20181122_114521, and size 256556
11-23 10:55:06.912 23948-23948/com.taggery I/TWC: TNRawHttp:        -1323506380 | 11/23/10:55:06.912 | INFO     | 29     | TNRawHttp | trying to sendRequest to https://mcs.us1.twilio.com/v1/Services/IS29a0bc76d13c433188a40bf60a4b5600/Media/ME13baad1cb72306020f5d72388545a8e2
11-23 10:55:08.216 23948-24306/com.taggery I/TWC: TMD:         2068318496 | 11/23/10:55:08.216 | INFO     | TMD | downloading media with id: MEfce338b4ee081845bcf587ded57e4980
11-23 10:55:08.222 23948-24306/com.taggery I/TWC: TMD:         2068318496 | 11/23/10:55:08.222 | INFO     | TMD | [GSIWs] stream created for request to: https://mcs.us1.twilio.com/v1/Services/IS29a0bc76d13c433188a40bf60a4b5600/Media/MEfce338b4ee081845bcf587ded57e4980/Content
11-23 10:55:08.228 23948-24306/com.taggery I/TWC: TNRawHttp:         2068318496 | 11/23/10:55:08.227 | INFO     | 29     | TNRawHttp | trying to sendRequest to https://mcs.us1.twilio.com/v1/Services/IS29a0bc76d13c433188a40bf60a4b5600/Media/MEfce338b4ee081845bcf587ded57e4980/Content
11-23 10:55:08.228 23948-24306/com.taggery I/TWC: IPM:         2068318496 | 11/23/10:55:08.228 | INFO     | IPM | [iMmy2] media download: started
11-23 10:55:08.546 23948-23948/com.taggery I/chatadpater: Download started
11-23 10:55:09.158 23948-24306/com.taggery I/TWC: TNRawHttp:         2068318496 | 11/23/10:55:09.158 | INFO     | 29     | TNRawHttp | trying to sendRequest to https://media.us1.twilio.com/MEfce338b4ee081845bcf587ded57e4980?Expires=1542951009&Signature=TAlTYd7KDYyisD23R6BIc18xL9C18YCPQq9LfhwX8Y2CaOdG5f8gGo-~O2089sqd42nXTjBTWdz21Yp7DEXqfLn5SL3yyHa7iZzyv7u-g4fflzdI9SCMtHwSU3zhSvntMHeQp40z4Hz6NyGXw9wCBuQarIF0ftVtoP6a781KxgHBbVnW2DTueK1UL-2NfycFiKvOtA7MwvKCGIsIDxo1alcyeMEa-hS400Dajo~nwBon9Nw6pPovWlWHbdwGPY4w4pzdXI8IPiynctn979tsUHo63Q3b8AgtLDfH3yKs-TIhAaBBxy79svGNWN7q3uTql3qg9NNcUcSfoK5Do5LjJA__&Key-Pair-Id=APKAJWF6YVTMIIYOF3AA
11-23 10:55:09.478 23948-23948/com.taggery I/chatadpater: Downloaded 0 bytes
11-23 10:55:10.945 23948-24306/com.taggery W/TWC: TNRawHttp:         2068318496 | 11/23/10:55:10.945 | WARNING  | 29     | TNRawHttp | Poco exception while sending request over http: Timeout: connect timed out: [2600:9000:211b:1400:10:b8cb:41c0:93a1]:443
11-23 10:55:10.946 23948-24306/com.taggery E/TWC: IPM:         2068318496 | 11/23/10:55:10.946 | CRITICAL | IPM | [iMmy2] media download: failed 0 Poco exception while sending request over http: Timeout: connect timed out: [2600:9000:211b:1400:10:b8cb:41c0:93a1]:443
11-23 10:55:10.956 23948-23948/com.taggery I/chatadpater: Error downloading mediaError 0:0 Poco exception while sending request over http: Timeout: connect timed out: [2600:9000:211b:1400:10:b8cb:41c0:93a1]:443
11-23 10:55:12.292 23948-24306/com.taggery W/TWC: TNRawHttp:         2068318496 | 11/23/10:55:12.292 | WARNING  | 29     | TNRawHttp | Poco exception while sending request over http: Timeout: connect timed out: [2600:9000:211b:a000:10:b8cb:41c0:93a1]:443
11-23 10:55:12.292 23948-24306/com.taggery E/TWC: IPM:         2068318496 | 11/23/10:55:12.292 | CRITICAL | IPM | [cTMnG] media download: failed 0 Poco exception while sending request over http: Timeout: connect timed out: [2600:9000:211b:a000:10:b8cb:41c0:93a1]:443

**Comment by berkus** [comment]
Hi, can you check with 4.0.0-rc18 and post here if anything changes?

**Comment by berkus** [comment]
Closing, no response.
