### ISSUE TITLE
com.twilio.exception.ApiException: /Services/../Channels/../Members/.. was not found

### ISSUE THREAD

**Issue by InI4** [twilio/twilio-chat-demo-android#78]
### Description

When new users logon into my app, they get registered in 4 special purpose channels. This happens on the server side. It is only now, that I inspect the server logs and realize that since at least 7 days (no older logs available), only 3 of these 4 registrations work. It seems to be always the same channel that works and the 3 others fail.

### Steps to Reproduce

See code below.

#### Code (optional)

```java
    ..
    channel(true, Constants.CH_SID_GUEST, identity);
    channel(true, Constants.CH_SID_TESTERS, identity);
    channel(true, Constants.CH_SID_PLAYER, identity);
    channel(true, Constants.CH_SID_SUPER, identity);
    ..
    private static void channel(boolean in, String channelSid, String identity) {
        // Proof this against Twilio using GAE-forbidden APIs
        try {
            Object res;
            try {
                if (in) {
                    res = Member.creator(TwilioConstants.TWILIO_IPM_SERVICE_SID, channelSid,
                            identity).create();
                } else {
                    res = Member.deleter(TwilioConstants.TWILIO_IPM_SERVICE_SID, channelSid,
                            identity).delete();
                }
            } catch (Exception ex) {
                res = ex;
            }
            L.info("* " + in + " " + channelSid + " " + identity + " " + res);
        } catch ( Exception ex ) {
            L.log(Level.SEVERE, "Twilio issues", ex);
        }
    }
    ..
```
Yes, the exception handling is bad, will improve on that soon, however this code and these channels were running flawless for a year or so.

#### Expected Behavior

User registered to channel.

#### Actual Behavior

Exception, I only have the wrapped, aforementioned one:

com.twilio.exception.ApiException: The requested resource /Services/../Channels/../Members/.. was not found

#### Reproduces how Often

100%

### Versions

All relevant version information for issue.

    compile 'com.twilio.sdk:twilio:7.30.0'

What I will do next: 
1. check if Twilio has removed channels of mine.
2. check if it is an issue with sdk 7.30.0.

**Comment by InI4** [comment]
I need to investigate more, might then reopen. Sry.

**Comment by berkus** [comment]
`com.twilio.sdk` is REST API not the sdk, despite the name. If you're using REST API in the application, this means you have your admin access credentials somehow stored in the application, this means somebody (anybody) could reverse engineer your app and gain control over your Twilio account.

**Comment by InI4** [comment]
I have an App, a LAMP server and a cloud service in my system. 

This is about running on my Google App Engine, mainly for creating those tokens the App forwards to the Twilio service. At times this server does some shuffling of users/players in certain chats and this seems to have had a problem with 7.30.0 lately (not before), but looks better unter 7.31.0. App is on com.twilio:chat-android:3.1.1, as I cannot go to the 4 branch.

**Comment by berkus** [comment]
This github project is specifically about 'com.twilio:chat-android' and not 'com.twilio.sdk'.

**Comment by InI4** [comment]
Sry, where to go for SDK stuff (I closed this one anyway as you saw).

**Comment by berkus** [comment]
I recommend going through support@twilio in this case as SDK don't have a public github repository (I think).
