### ISSUE TITLE
Application crash when getting channels last messages

### ISSUE THREAD

**Issue by jermeyyy** [twilio/twilio-chat-demo-android#8]
After few subsequent requests application freezes with black screen and crashes afterwards.
What I found in stacktrace:
`com.twilio.chat.demo.debug D/TWC: Messages(native):        -1621898960 | 05/19/13:48:41.345 | DEBUG    | Messages(native) | Messages loaded successfully
com.twilio.chat.demo.debug D/TWC: EntityCache:        -1621898960 | 05/19/13:48:41.346 | DEBUG    | EntityCache | Returning Java object from cache
com.twilio.chat.demo.debug D/TWC: EntityCache:        -1621898960 | 05/19/13:48:41.346 | DEBUG    | EntityCache | Creating new Java object
com.twilio.chat.demo.debug W/art: Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[25,tid=29342,Native,Thread*=0x9f64fc00,peer=0x12c96880,"o.debug - 29093 - 29342"]`

I think that it is some issue with SDKs native library implementation.

**Comment by berkus** [comment]
The lines you posted are not relevant, please take a look in REPORTING_BUGS.md in the repository and send a proer complete log. 

Thanks!

**Comment by berkus** [comment]
I'm closing this one since there is no response, please reopen if you get the logs.
