### ISSUE TITLE
java.lang.NoSuchFieldError: No static field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; in class Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; or its superclasses (declaration of 'org.apache.http.conn.ssl.AllowAllHostnameVerifier' appears in /system/framework/framework.jar:classes2.dex)

### ISSUE THREAD

**Issue by GarviShah** [twilio/twilio-chat-demo-android#81]
When i am trying to execute create binding code for sending notification using FCM i am getting this issue.

Here is the create binding code,

  ```
Twilio.init(ACCOUNT_SID, AUTH_TOKEN);
        Binding binding = Binding.creator(
                "ISXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
                "identity", //Friendly name given by me like "T20"
                Binding.BindingType.FCM,
                "address") // Fcm token
            .create();

        System.out.println(binding.getSid());
```

I am following this link of Twilio official doc "https://www.twilio.com/docs/notify/send-notifications".

Whenever i execute 1st step "Bindings recourse" it shows me error like this : "java.lang.NoSuchFieldError: No static field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; in class Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; or its superclasses (declaration of 'org.apache.http.conn.ssl.AllowAllHostnameVerifier' appears in /system/framework/framework.jar:classes2.dex)"

**Comment by berkus** [comment]
This is a wrong project for this, contact twilio support please - twilio.com/support

**Comment by GarviShah** [comment]
Can you please suggest me which is the right way to send push notification in chat?

**Comment by berkus** [comment]
Chat does not use the autogenerated SDK, it uses Twilio Chat SDK which is a completely different product - see https://www.twilio.com/docs/chat/android - there is a link to configuring Push notifications as well.
