### ISSUE TITLE
Unread Count Message in channel

### ISSUE THREAD

**Issue by rakeshkatta1311** [twilio/twilio-chat-demo-android#82]
Hi,

How can I get unread message count in channel in case of channel status is UNJOINED. 

I want to show unread count in my chat list screen for each of chat. Is there any function which can return the count of unread message whether channel is joined or not.

Thanks,
Rakesh

**Comment by berkus** [comment]
If you have not joined a channel, then number of unread messages equals total number of messages in the channel.

**Comment by berkus** [comment]
Closing as no response.
