### ISSUE TITLE
unable to connect to twilio sync

### ISSUE THREAD

**Issue by haseebehsan** [twilio/twilio-chat-demo-android#87]
> Before filing an issue please check that the issue is not already addressed by the following:
>  * [Github Issues](https://github.com/twilio/twilio-chat-demo-android/issues)
>  * [Changelog](https://www.twilio.com/docs/api/chat/changelogs/android)

### Description

I'm running the java code on android, it fetches jwt token from my server i can see in logs, but after pressing log-in after waiting a while on loading screen this toast comes
Error Logging in : Error 0:1401 Unable to establish connection to Twilio sync services.

#### Expected Behavior

should log in

#### Actual Behavior

throws an error "Error Logging in : Error 0:1401 Unable to establish connection to Twilio sync services."

#### Reproduces how Often

every time

### Versions

All relevant version information for issue.

    compile 'com.android.support:support-v4:23.3.0+'
    compile 'com.google.firebase:firebase-messaging:10.2.0' // FCM
    compile 'com.google.android.gms:play-services-base:10.2.0'
    compile 'uk.co.ribot:easyadapter:1.5.0@aar'
    compile 'com.twilio:chat-android:4.0.0'
    compile 'com.twilio:accessmanager-android:0.1.0'

#### Logs

[Logs.txt](https://github.com/twilio/twilio-chat-demo-android/files/2782872/Logs.txt)

#### Android API

26

#### Android Device

Redmi S2

**Comment by haseebehsan** [comment]
![screenshot_2019-01-22-17-27-43-010_com twilio chat demo debug](https://user-images.githubusercontent.com/10743165/51537590-c6ae6880-1e70-11e9-830e-d8981a9d92e8.png)
here is the screenshot of issue

**Comment by sam2820** [comment]
i am also facing same issue

**Comment by berkus** [comment]
Please check your network connectivity with twilio.

Also providing full logs will help to determine the root cause - the how to is described [here](https://github.com/twilio/twilio-chat-demo-android/blob/master/REPORT_BUGS.md).

**Comment by haseebehsan** [comment]
I did contact Twilio support and found the problem
@sam2820 it might help you too
The problem was with the token string, token that android app received had double quotes around it as part of it, just had to get it removed and it worked fine.
@sam2820 if it doesn't help contact Twilio support with full logs, they will help you
and thanks @berkus 
Regards

**Comment by berkus** [comment]
@haseebehsan cool, great they helped you!
