### ISSUE TITLE
Token generator problems (was: cannot build)

### ISSUE THREAD

**Issue by MinkushNimbusClinic** [twilio/twilio-chat-demo-android#9]
I get the error when i try to make build ...Error:Execution failed for task ':chat-demo-android:processDebugGoogleServices'. > No matching client found for package name 'com.twilio.chat.demo.debug'

**Comment by ravichoudhary33** [comment]
I am getting same error, please help

**Comment by berkus** [comment]
You have to generate google-services.json with the matching package name. This is described in the readme.

**Comment by ravichoudhary33** [comment]
@berkus after following the readme instruction, i am getting this error

**Comment by ravichoudhary33** [comment]
Information:Gradle tasks [clean, :chat-demo-android:generateDebugSources, :chat-demo-android:mockableAndroidJar, :chat-demo-android:prepareDebugUnitTestDependencies, :chat-demo-android:generateDebugAndroidTestSources, :chat-demo-android:compileDebugSources, :chat-demo-android:compileDebugUnitTestSources, :chat-demo-android:compileDebugAndroidTestSources]

Error:Execution failed for task ':chat-demo-android:processDebugGoogleServices'.
> No matching client found for package name 'com.twilio.chat.demo.debug'

**Comment by berkus** [comment]
Did you generate google-services.json for com.twilio.chat.demo.debug application id?

**Comment by ravichoudhary33** [comment]
@berkus No, I had used com.twilio.chat.demo , but again created json for com.twilio.chat.demo.debug and fixed the error. Now the app is running but I have a doubt regarding the app, in the login page what should i enter in client name, by using the default one TestUser and any random name i am getting error like : Error Logging in: Error 0:6 EMS service could not authenticate/authorize ether provided customer fpa token or twilio rtd token, unable to set FPA token, please help

**Comment by berkus** [comment]
Can you post the token you use?

**Comment by ravichoudhary33** [comment]
I only added my server url generated by ngrok in build.gradle file in this line of code:
def ACCESS_TOKEN_SERVICE_URL = project.hasProperty('ACCESS_TOKEN_SERVICE_URL') ? "\""+project.getProperty('ACCESS_TOKEN_SERVICE_URL')+"\"" : "\"http://fdf8f750.ngrok.io/token\""

**Comment by berkus** [comment]
My question was - does your token generator generate proper token? With Chat grants?

**Comment by ravichoudhary33** [comment]
can you please explain what are you talking about? Do i need to add extra code in demo app ? In BasicChatClient.java class accessToken is generated and this access token is same as what i am getting on the local server. I don't know what do you mean by proper token & can you explain what is chat grants? please

**Comment by berkus** [comment]
Could you please post the token provided by your generator at http://fdf8f750.ngrok.io/token ?

**Comment by ravichoudhary33** [comment]
{"identity":"JeromeJohnston60942","token":"eyJjdHkiOiJ0d2lsaW8tZnBhO3Y9MSIsInR5cCI6IkpXVCIsImFsZyI6IkhTMjU2In0.eyJpc3MiOiJTSzVmMGRlZGI0NzI5NTg2NGYzMmZkMTg5NGJhODgwZjViIiwiZXhwIjoxNDk3MjUzNjIwLCJncmFudHMiOnsiaWRlbnRpdHkiOiJKZXJvbWVKb2huc3RvbjYwOTQyIiwiZGF0YV9zeW5jIjp7InNlcnZpY2Vfc2lkIjoiIiwiZW5kcG9pbnRfaWQiOm51bGx9LCJpcF9tZXNzYWdpbmciOnsic2VydmljZV9zaWQiOiJJU2NhODdlNTU5OGM3ODRiMDlhOGViYzdlOTQwMzU3YTFkIiwiZGVwbG95bWVudF9yb2xlX3NpZCI6bnVsbCwiZW5kcG9pbnRfaWQiOm51bGwsInB1c2hfY3JlZGVudGlhbF9zaWQiOm51bGx9LCJ2aWRlbyI6e319LCJqdGkiOiJTSzVmMGRlZGI0NzI5NTg2NGYzMmZkMTg5NGJhODgwZjViLTE0OTcyNTAwNDgiLCJzdWIiOiJBQ2U2ZGZjYzFkN2IxNTQ0NTgyMDczZDJmZTEyYTlhNTE2In0.K4aBPdBwG_JBApg-0NcAwgWpP3PvxMyHNY_adW3b2yI"}

**Comment by ravichoudhary33** [comment]
hey @berkus please help man i am stuck..

**Comment by berkus** [comment]
I've added support for quickstart format tokens to this repository, please update to the latest version and try again.

Reopen if you still have any problems.

**Comment by wuguanyu** [comment]
i still have this problem

**Comment by wuguanyu** [comment]
ChatSDKcreateChatClient onConectionErrorEMS service could not authenticate/authorize ether provided customer fpa token or twilio rtd token, unable to set FPA token-6

**Comment by berkus** [comment]
@wuguanyu you need to provide a token you used, some expired one will do.

**Comment by berkus** [comment]
Since there's no response, I'm closing this one.

**Comment by Filipe-Ramos** [comment]
Hi. I'm having a similar problem:

    EMS service could not authenticate/authorize ether provided customer fpa token or twilio rtd token, unable to set FPA token

Used token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzY29wZSI6InNjb3BlOmNsaWVudDppbmNvbWluZz9jbGllbnROYW1lPTJkIHNjb3BlOmNsaWVudDpvdXRnb2luZz9hcHBTaWQ9QVBYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWCIsImlzcyI6IkFDMWJmZGVkMjY1YzExOWIzZjMyMWUyNjUxYjI0OGVhODMiLCJleHAiOjE0OTc5ODcwMjksImlhdCI6MTQ5Nzk4MzQyOX0.wFUBXA2BmCPijIsGZ-4vbjmAm7K52W-qVnLT4YSqrXw

**Comment by berkus** [comment]
@Filipe-Ramos you are using an invalid token, this is token for Twilio Client, SIP.

You need to use a Twilio Chat token as described in the [documentation](https://github.com/twilio/twilio-chat-demo-android/issues/9#issuecomment-307715944).

**Comment by hb9eik** [comment]
Hi. I'm having a similar problem:
'{"message":"The authorization with Token failed","code":2016,"user_error":false,"params":{"description":"Could not authenticate fpa token"}}'

eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImN0eSI6InR3aWxpby1mcGE7dj0xIn0.eyJqdGkiOiJBUFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYLTE0OTgwNzE3NDIiLCJncmFudHMiOnsiaWRlbnRpdHkiOiJnZnJhbnphQHNpY2VmLmNoIiwiaXBfbWVzc2FnaW5nIjp7InNlcnZpY2Vfc2lkIjoiSVNjMWFmZTdjZTJjMjE0NDUzYWU4MWVhYzkyZDdhZDJiMiIsImVuZHBvaW50X2lkIjoic2l3ZWdvLW12cDE6Z2ZyYW56YUBzaWNlZi5jaDpzb21laW9zZGV2aWNlaWQifX0sImlhdCI6MTQ5ODA3MTc0MiwiZXhwIjoxNDk4MDc1MzQyLCJpc3MiOiJBUFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYIiwic3ViIjoiQUMxYmZkZWQyNjVjMTE5YjNmMzIxZTI2NTFiMjQ4ZWE4MyJ9.3E52gud2AGH19Wc-LXEe7jW6gp9wFD1fjD2jqbwT1lQ

**Comment by Naroh091** [comment]
So the demo should work with the tokens generated by the Quickstart guides? Using this token (which is the one generated by default by the quickstart php server):

{
identity: "RowdyWendyKane",
token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImN0eSI6InR3aWxpby1mcGE7dj0xIn0.eyJqdGkiOiJTSzczNTlhNTVhNzY5NmJhODAxN2E1ZWFjYmZhMTdhMmI0LTE1MDE5NjY1MjciLCJpc3MiOiJTSzczNTlhNTVhNzY5NmJhODAxN2E1ZWFjYmZhMTdhMmI0Iiwic3ViIjoiQUMyODYzNDZmOGIwOGQ5NjRhMmI1YTFmNzhlNTUzMDJjYSIsImV4cCI6MTUwMTk3MDEyNywiZ3JhbnRzIjp7ImlkZW50aXR5IjoiUm93ZHlXZW5keUthbmUiLCJ2aWRlbyI6e30sImlwX21lc3NhZ2luZyI6eyJzZXJ2aWNlX3NpZCI6IklTYTI2ZDYxMmM1NmM0NGExYjhkMWVjMzQ0ZGExN2Y0NGUifX19.7FBs52NUd7jGlV12vfJYIB-Q7h7J6m9hyrrBEmMUvG8"
}

I'm getting exactly the same error: EMS service could not authenticate/authorize ether provided customer fpa token or twilio rtd token, unable to set FPA token.

**Comment by berkus** [comment]
Yes, it is supported by the demo app - see code here https://github.com/twilio/twilio-chat-demo-android/blob/master/chat-demo-android/src/main/java/com/twilio/chat/demo/HttpHelper.java#L47

**Comment by shrishailcne** [comment]
eyJjdHkiOiJ0d2lsaW8tZnBhO3Y9MSIsInR5cCI6IkpXVCIsImFsZyI6IkhTMjU2In0.eyJpc3MiOiJTSzk2Mjk2MjAxNTA5M2YyNTNkMzA0YzIxNGUwY2I0NjgyIiwiZXhwIjoxNTMwNjE3MDMwLCJncmFudHMiOnsiaWRlbnRpdHkiOiJTaHJpc2hhaWwiLCJjaGF0Ijp7InNlcnZpY2Vfc2lkIjoiSVM2NTJjMjFhMGJiZGY0Y2NmOTgzYjI0NDVkNDYyNzQ3MyIsImRlcGxveW1lbnRfcm9sZV9zaWQiOm51bGwsImVuZHBvaW50X2lkIjpudWxsLCJwdXNoX2NyZWRlbnRpYWxfc2lkIjpudWxsfSwiZGF0YV9zeW5jIjp7InNlcnZpY2Vfc2lkIjoiZGVmYXVsdCIsImVuZHBvaW50X2lkIjpudWxsfSwidmlkZW8iOnt9fSwianRpIjoiU0s5NjI5NjIwMTUwOTNmMjUzZDMwNGMyMTRlMGNiNDY4Mi0xNTMwNjEzNTA0Iiwic3ViIjoiQUNmMTk5NjkyNTVlNDBmYjZhNGFkOWFmMTEyOTBiNzExNyJ9.6nJ2-dWCNTqbRXQRHoypjM4jk85-oT_D1dEmNA31Hww

**Comment by shrishailcne** [comment]
I am also getting same error for this token

**Comment by berkus** [comment]
@shrishailcne you have invalid `endpoint_id` in your token, please remove it from generated tokens completely.

**Comment by shrishailcne** [comment]
@berkus  How can i remove it is generated automatically.

**Comment by berkus** [comment]
Change your generator's code to not generate it.

**Comment by shrishailcne** [comment]
Same issue i am facing after removing endpoint_id.

**Comment by berkus** [comment]
Open a new ticket please, this one is closed.
