### ISSUE TITLE
Is there any callback when channel's attribute is changed?

### ISSUE THREAD

**Issue by strider1981** [twilio/twilio-chat-demo-android#96]
This is a question rather than a bug. I need to know if there is any callback when I update a channel's attribute? I was looking at `ChannelListener.onSynchronizationChanged` callback but that does not seem to be doing the trick. I what I need to do is when a user's changes channel's attribute other users in the group should get a callback. Is that possible? If yes, how? Please let me know. Thanks.

**Comment by aleksandrsivanovs** [comment]
Hi!

You can use ChatClientListener's onChannelUpdated. 
(https://media.twiliocdn.com/sdk/android/chat/releases/4.0.4/docs/interfacecom_1_1twilio_1_1chat_1_1ChatClientListener.html#afeba9715c7ee2376b2badf1fc630292e)
