### ISSUE TITLE
Twilio chat NotificationPayload does not contain getChannelId()

### ISSUE THREAD

**Issue by astamato** [twilio/twilio-chat-demo-android#98]
We've noticed an inconsistency while working with push notifications for chat in Android.

[NotificationPayload class](https://media.twiliocdn.com/sdk/android/chat/releases/4.2.0/docs/classcom_1_1twilio_1_1chat_1_1NotificationPayload.html) has method `getChannelSid()` to retrieve `channel_sid` and `getChannelTitle()` to retrieve `channel_title`. What we've noticed:

1) We don't have public method to retrieve `channel_id` for payload (like we do for channel_sid).
2) getChannelTitle() method is actually retrieving what we would've considered channel_id as opposed to the actual channel title.

Right now when receiving push, because we need to have channel_id to do some further processing, we're calling/using getChannelTitle(). We're unsure if this is the correct way to go, if this is working as designed, if this is a bug. From the documentation is a bit unclear why we're receiving parameters like this, and we'd expect to have proper getChannelId() returning channel_id method.

#### Chat Android SDK

"com.twilio:chat-android:4.2.0"

Cheers!

**Comment by berkus** [comment]
Hi!

1. `channel_id` is the obsolete name for `channel_sid` in payload. It returns the same value. You should use getChannelSID() to retrieve the SID.

2. getChannelTitle() returns SID for you because you didn't set either Unique Name or Friendly Name for the channel.

Cheers!

**Comment by astamato** [comment]
Hey,

Ok, I believe this makes sense.
Then again, what if I set both Unique Name and Friendly Name? I believe getChannelTitle() returns uniqueName right? In that case how to access Friendly Name?

Hope this question makes sense still.

Cheers;

**Comment by astamato** [comment]
Hey,

Thank you very much for your answer. I believe this makes sense.
Then again, what if, for some reason, I set both Unique Name and Friendly Name? I believe getChannelTitle() returns uniqueName right? In that case how to access Friendly Name?

Hope this question makes sense still.

Cheers;

**Comment by berkus** [comment]
Hi,

yes, if you set Unique Name then the only way to get Friendly Name is to instantiate the chat clientm, get channel descriptor by sid or unique name and then retrieve its Friendly Name.
If you absolutely need friendly name in the notification payload - just don't set Unique Name. You can always get by using SID instead of Unique Name (they serve pretty much the same purpose - uniquely identifying your channel).

Hope this helps.
