### ISSUE TITLE
Error 0:50107 User not authorized for command. When I try to change message attributes

### ISSUE THREAD

**Issue by nikdevpub** [twilio/twilio-chat-demo-android#99]
When changing attributes on IOS, everything works well, but on Android I get an error message: "0:50107 User not authorized for command"
com.twilio:chat-android:4.2.0
`
 private fun initChatClient(chatData: ChatData) {
        viewState.setChatData(chatData)
        Timber.d(chatData.identity)
        val props = ChatClient.Properties.Builder()
            .createProperties()
        Timber.d(chatData.toString())
        ChatClient.create(
            context,
            chatData.access_token,
            props,
            object : CallbackListener<ChatClient>() {
                override fun onSuccess(chatClient: ChatClient) {
                    this@ChatPresenter.chatClient = chatClient
                    loadChannels(chatData.identity)
                    Timber.d("Success creating Twilio Chat Client")
                }

                override fun onError(errorInfo: ErrorInfo) {
                    Timber.d("Error creating Twilio Chat Client: " + errorInfo.message)
                    viewState.showError(errorInfo.message)
                }
            }
        )
    }

    private fun loadChannels(identity: String) {

        chatClient?.channels?.getChannel(identity, object : CallbackListener<Channel>() {
            override fun onSuccess(channel: Channel?) {
                if (channel != null) {
                    Timber.d("Joining Channel")
                    joinChannel(channel)
                } else {
                    Timber.d("Creating Channel")

                    chatClient?.channels?.createChannel(
                        identity,
                        Channel.ChannelType.PRIVATE, object : CallbackListener<Channel>() {
                            override fun onSuccess(channel: Channel?) {
                                if (channel != null) {
                                    Timber.d("Joining Channel")
                                    joinChannel(channel)
                                }
                            }

                            override fun onError(errorInfo: ErrorInfo?) {
                                Timber.d("Error creating channel: " + errorInfo!!.message)
                                viewState.showError(errorInfo.message)
                            }
                        })
                }
            }

            override fun onError(errorInfo: ErrorInfo?) {
                Timber.d("Error retrieving channel: " + errorInfo!!.message)
                loadChannels(identity)
            }

        })
    }

    private fun joinChannel(channel: Channel) {
        Timber.d("Joining Channel: " + channel.uniqueName + " - " + channel.status + "-- " + channel.messages)
        this@ChatPresenter.generalChannel = channel
        listenGeneralChanel()

        if (channel.status != Channel.ChannelStatus.JOINED) {
            channel.join(object : StatusListener() {
                override fun onSuccess() {
                    this@ChatPresenter.generalChannel = channel
                    Timber.d("Joined default channel")
                    listenGeneralChanel()
                }

                override fun onError(errorInfo: ErrorInfo) {
                    Timber.d("Error joining channel: " + errorInfo.message)
                }
            })
        }
    }

private fun loadMessages() {
        viewState.setMessageListLoading(true)
        isNextPageLoading = true

        generalChannel?.messages?.getLastMessages(ITEMS_ON_PAGE, object : CallbackListener<List<Message>>() {
            override fun onSuccess(messages: List<Message>?) {
                if (messages != null && !messages.isEmpty()) viewState.setMessageList(messages)
                viewState.setMessageListLoading(false)
                currentShownMessagesCount = ITEMS_ON_PAGE.toLong()
                isNextPageLoading = false
                Timber.d("getLastMessages")
            }

            override fun onError(errorInfo: ErrorInfo?) {
                super.onError(errorInfo)
                viewState.showError(errorInfo?.message)
                Timber.d(errorInfo!!.message)
                isNextPageLoading = false
                viewState.setMessageListLoading(false)
            }
        })
    }
`

**Comment by berkus** [comment]
Closing as apparently resolved.
